### ISSUE TITLE
In which cases it is not necessary to change the version of my product.

### ISSUE THREAD

**Issue by 90dread** [semver/semver#1013]
I have a product that contains APIS and this product contains subscription plans. Added a new consumption plan for existing APIS or simply changed the name of the product owner. Should I change the version number? What would it be assuming that the product is in version 1.0.0?

**Comment by ljharb** [comment]
if you added a new thing, it's semver-minor.

**Comment by steveklabnik** [comment]
SemVer is generally better for libraries, which have code as their users, than applications, which have humans as their users.

If code needs to change to work, it's semver major.

If code doesn't need to change to work, but you need to add more code to support new features, it's semver minor.

If code doesn't need to change at all, and by updating you get bug fixes, it's semver patch.
