### ISSUE TITLE
Why suggested regexes have not used atomic groupings or possive quantifiers?

### ISSUE THREAD

**Issue by LastKnightXZ** [semver/semver#1049]
In suggested regex like [named group regex](https://regex101.com/r/Ly7O1x/3/)
`^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`

why are we not using atomic grouping or possessive like [this](https://regex101.com/r/yoWJvz/1)
`^(?>(?P<major>0|[1-9]\d*+))\.(?>(?P<minor>0|[1-9]\d*+))\.(?>(?P<patch>0|[1-9]\d*+))(?:-(?P<prerelease>(?:0|[1-9]\d*+|\d*+[a-zA-Z-][0-9a-zA-Z-]*+)(?:\.(?:0|[1-9]\d*+|\d*+[a-zA-Z-][0-9a-zA-Z-]*+))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]++(?:\.[0-9a-zA-Z-]++)*+))?$`

note: added atomic grouping / possessive quantifiers all places i can think of, except for prerelease as we need to backtrack for prerelease segments with '0' as beginning, and it matches sames cases (do tell me if there are exceptions)

It would removes instances of unnecessary backtracking on mismatch,
and keeps thing clear which segments are not expected to backtrack.

Is it because many regex engine doesn't support atomic grouping / possessive quantifiers?

**Comment by steveklabnik** [comment]
Because the regexes are community contributed best efforts.

To be honest, I am kind of regretting including them. But, if you feel something is better, feel free to submit a PR.
