### ISSUE TITLE
branch for 3.0.0

### ISSUE THREAD

**Issue by petermichaux** [semver/semver#113]
Several larger spec changes are being proposed, for example, #110. If they are too late for version 2 then can a version 3 branch be created where larger changes could be merged?

**Comment by jwdonahue** [comment]
@petermichaux, can we please close this old issue? Somebody needs to create a 3.0.0 branch or decide not to ([@haacked's comment](https://github.com/semver/semver/issues/113#issuecomment-19659018). Either way, this ancient issue should be closed.

**Comment by FichteFoll** [comment]
Imo the discussion about Version selection is still valid to this day, although the issue title is kind of misleading about the content.

**Comment by petermichaux** [comment]
I don't really remember this issue. Close if you like. :-)

**Comment by jwdonahue** [comment]
I believe @Haacked [answered](https://github.com/semver/semver/issues/113#issuecomment-19659018) @petermichaux 's question. It seems the matter was decided, but I can only recommend closure at this point in time.

**Comment by jwdonahue** [comment]
@petermichaux, please close this issue at your earliest possible convenience.  Thank you.

**Comment by jwdonahue** [comment]
@petermichaux, can you please close this thread?  I don't have the special sauce, but you can close your own issue.   Thank you.
