### ISSUE TITLE
If this a valid (half-automatic) workflow

### ISSUE THREAD

**Issue by DoCode** [semver/semver#119]
![image](https://f.cloud.github.com/assets/1489133/658728/1c70cde6-d609-11e2-9617-3501cb96034d.png)

I hope we can discuss it here...
Greets

**Comment by jwdonahue** [comment]
@DoCode, I agree with @tbull, your table doesn't make any sense to me either.  Since this issue will not result in a PR and nobody else seems to have engaged on this issue, please close it at your earliest possible convenience.

**Comment by silkentrance** [comment]
Why do you not just close the issue in order to get rid of it? SEMVER is not about CI or defining any kind of process, it is an utility for making defined processes happen.

**Comment by jwdonahue** [comment]
@DoCode, please close this issue at your earliest possible convenience.  Thank you.

**Comment by DoCode** [comment]
Closed by design
