### ISSUE TITLE
Change log for SemVer 2.0

### ISSUE THREAD

**Issue by mnapoli** [semver/semver#143]
SemVer 2.0 _needs_ a change log. What has fundamentally changed since 1.\* version that requires us to change anything?

This is the basics of versioning ;)

**Comment by jwdonahue** [comment]
@mnapoli, unless you wish to pursue this issue further, please close it at your earliest possible convenience.

**Comment by gregmac** [comment]
So from what I see:

## Breaking changes from Semver 1.0.0 to 2.0.0:

* Each digit of the version number must now be non-negative. 1.x only specified they are "integers" ([Section 2](https://semver.org/#spec-item-2), https://github.com/semver/semver.org/issues/47)
* Each digit of the version number must not contain non-leading zeros, which was previously unspecified ([Section 2](https://semver.org/#spec-item-2), #115)
* Build metadata can be added by appending a plus sign ([Section 10](https://semver.org/#spec-item-10), #77)

## Other major changes

* Numbers can now be incremented by a value greater than one, 1.x said increment by one ([Section 2](https://semver.org/#spec-item-2), 2bfa9b0)
* Deprecation requires incrementing minor version ([Section 7](https://semver.org/#spec-item-7), https://github.com/semver/semver.org/issues/24)
* SemVerTag is no longer part of the spec (52c9b2b)
* Precedence rules added ([Section 11](https://semver.org/#spec-item-11), 84c9618)


Diff: [Code](https://github.com/semver/semver/compare/v1.0.0...v2.0.0?diff=unified&source=false#files_bucket) | [Commits](https://github.com/semver/semver/compare/v1.0.0...v2.0.0)
