### ISSUE TITLE
What about refactoring?

### ISSUE THREAD

**Issue by openjck** [semver/semver#146]
Semantic Versioning holds that the patch version should be incremented for...

> backwards-compatible bug fixes

but that... 

> Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.

Where does refactoring fit into this? Refactored code is modified code, but the modifications do not necessarily contain any bug fixes.

**Comment by tebanep** [comment]
I think PATCH should also take into account refactoring as the process could both introduce new bugs or create performance improvements and users should know. Though the API has not changed, the program they are using is not the same that is being newly released, and this can create confusion.

**Comment by benwiley4000** [comment]
Maybe the times have changed, but the thought of sneaking refactoring changes into an existing release sounds like blasphemy to me! Might just be the school of npm, which discards the possibility of doing that...

Anyway, I came to this thread wondering what the standard versioning procedure should be for refactoring/optimizations, and it seems like there isn't yet a solid recommendation.

My leaning is: obvious refactoring should happen before a release is cut. After that release is cut, refactoring can wait - commit it to the repo, and include it with the next release. If the refactoring was vital, it was probably to address a performance issue, which counts as a bug - warranting a patch version bump.

Can we get some recommendation entered into the spec FAQ?

**Comment by binki** [comment]
Once a release is made, that release should never be changed. PATCH is used to indicate changes that *should not* break the API. This includes refactoring. Semver clearly states:

> Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.

Refactoring is a modification—even if it doesn’t cause any behavior change. You should be able to unambiguously identify the release pre-refactoring and post-refactoring.

The reason for requiring a new version for each released modification is that you might be mistaken and have accidentally introduced a behavior change. But that doesn’t mean that if you can skip the version increment if you can somehow “prove” that you didn’t introduce any behavior changes or bugs.

The only reason you would ever **want** to reuse a version number in a re-release after a refactoring or bugfix is if your API consumer is **not** using semver. Then the only way to get such a consumer to be willing to use the new release of the library is to re-use an existing version number. But, then, in such a situation, semver is not being respected, so the semver spec has nothing to say about that situation.

**Comment by Tieske** [comment]
@binki I think this is a solid reasoning on how to deal with it, within the boundaries of the current semver spec. 

But a FAQ entry explaining this as such would be nice.

**Comment by jwdonahue** [comment]
#339

**Comment by jwdonahue** [comment]
@openjck 

A refactor can be considered a patch-level change if nothing is broken by it. There MUST never be two packages with different contents, having the same version number. SemVer is as much about your what your customer's expect as it is about what you are saying with the version. Refactored code is simply not the same as the previous version and should therefore get a version bump.  Security conscious consumers need to know whether you've made changes to the code.

Please close this issue at your earliest possible convenience.

**Comment by openjck** [comment]
Is there plan to update the spec to make this clear? As described in the issue description, the spec contradicts itself right now.

**Comment by jwdonahue** [comment]
@openjck, clone semver/semver.org, make your proposed changes and issue a PR to semver/semver.org. Little discernible work has been going on here at semver/semver lately.  Personally, I think refactoring is in fact a bug fix, whether you actually wrote up a bug or work ticket to cover the changes, it's work done to remove accumulated engineering debt (design bugs) and falls into the category of bug fix, if no interface or behavioral changes were made.

**Comment by Tieske** [comment]
See #415

**Comment by jwdonahue** [comment]
@Tieske, please issue a pull request for [your proposed changes](https://github.com/Tieske/semver/commit/85ee7f8064601ca8c148fe78d6eba94367dd0434) to semver/semver.org, I like them, I will say so in a review of the code there, but I can't promise it will be accepted.

**Comment by Tieske** [comment]
@jwdonahue isn't `semver/semver` the source for `semver/semver.org` ?

**Comment by Tieske** [comment]
if not, then why are there 2 repos?

**Comment by jwdonahue** [comment]
@Tieske, I've asked that same question myself, no answer yet.  All the actual work appears to be a happening over on sermver/semver.org.

**Comment by Haacked** [comment]
semver/semver is the repository for the Semver specification. Any changes to the spec itself should go here. The semver/semver.org repository is the [Jekyll](https://jekyllrb.com/) repository that generates https://semver.org. Anything on the website that isn't in the spec should go there including translations and potentially supporting materials down the road.

**Comment by jwdonahue** [comment]
I think the readme.md file in each of the repositories should make it clear what they are each used for and provide links to the actual specification. Currently, the readme.md file in semver/semver, seems to be the spec itself.

**Comment by silkentrance** [comment]
While refactored code must never break existing tests, it might. If it breaks existing test, one would have to refactor the tests as well.

Get your gears straight.

@jwdonahue please close this regardless as it is nonsense.

**Comment by mjhpour** [comment]
Good article to handle refactor and release: [Four strategies to version APIs and services](https://www.ibm.com/developerworks/library/mw-1710-phillips/index.html)

**Comment by dorianneto** [comment]
Good discussion! This is something I had a lot of doubts about how to act. Thanks all!

**Comment by jwdonahue** [comment]
@openjck, can you please close this issue at your earliest possible convenience? We're trying to reduce the number of none actionable open issues.  Thank you.

**Comment by openjck** [comment]
I'm happy to close, but I don't think this is really resolved. The three categories&mdash;major, minor, and patch&mdash;are not mutually exclusive. Others have pointed to documentation improvements as something that is not obviously covered by any of them.

I'll close, but I'll recommend additional attention to #415.

**Comment by nsajko** [comment]
> We're trying to reduce the number of none actionable open issues.

How is this not actionable? It's simply a bug in the spec. The specification should make it clear what to do with:
* refactoring changes
* performance improvements
* doc changes
* etc

The ambiguity conflicts with the very purpose of Semver.

**Comment by ljharb** [comment]
@nsajko the specification already makes it clear. is it breaking something? major. is it adding something? minor. Is it *literally anything else, including an infinite list of things that it would be silly to enumerate*? patch.

**Comment by openjck** [comment]
> [@nsajko](https://github.com/nsajko) the specification already makes it clear. is it breaking something? major. is it adding something? minor. Is it _literally anything else, including an infinite list of things that it would be silly to enumerate_? patch.

Having thought about this a bit last night, I do think updating the patch number after refactoring makes the most sense, if the refactoring needs to be released at all. I think it's also fine not to release refactored code until something more meaningful changes.

However, respectfully, and without trying to be needlessly pedantic, the spec doesn't appear to say that. As far as I can tell, the spec only talks about the patch number in relation to bugs. Please correct me if I'm wrong.

If this issue hadn't seen much activity since I opened it, I wouldn't suggest this, but given that there's been a fair number of comments and emoji reactions, maybe it would be good, and even save you all some frustration, to very briefly mention in the docs that everything else (everything that isn't a breaking API change or a feature) can be reflected by an incremented patch number.

**Comment by haacked** [comment]
> Having thought about this a bit last night, I do think updating the patch number after refactoring makes the most sense

I think these are orthogonal concerns. If the refactoring introduces a breaking change, then the Major version should changed. If a new feature was added during the refactoring, then increment the minor. And if the refactoring fixes a bug or improves performance (which could be regarded as fixing a perf bug), then increment the patch.

If it's a rare "pure" refactoring and no behavior has changed, not even bug fixes, then what's the point of releasing it? Releasing it is a collective inconvenience to all the package consumers who will be told that there's a new version of the package only to discover there's no bug fixes. When I see a new version of a package, I like to find out what bugs were fixed. It would be a waste of my time to investigate a new patch version only to discover nothing's changed. It's a disservice to the package consumers for what benefit?

One of the key points of Semver is to help package consumers decide whether they'll take an upgrade or not. A new package version that isn't an upgrade seems like a pointless exercise. At most, make it a pre-release of the next patch version if you feel compelled to release the same version again.

**Comment by jwdonahue** [comment]
> Where does refactoring fit into this? Refactored code is modified code, but the modifications do not necessarily contain any bug fixes.

The reason the spec essentially says "one versioned artifact per unique version string", is to avoid ambiguity. If you have multiple packages, each claiming to to be the same version V of that package, but they have different content hashes, which one is the real version V? Was one of them tampered with? What other SemVer rules were violated?

When you refactor code, you are in fact, fixing a bug. Maybe it's not a customer visible bug, or you're organization uses something like a non-bug "work order" to kick-off the effort, but there is some inherent defect in the code that is being fixed by the refactoring. Engineer's do not modify code without some underlying reason(s). Whether you bump major, minor or patch, depends on the level of risk you are taking with the release of those refactored bits. If you've done your job correctly, you probably fixed a whole slew of code defects, so it's likely just a patch bump.

If you don't have any unit or acceptance tests to prove you didn't break anything, you might want to consider adding those, or giving your product a major bump, just in case.

**Comment by jwdonahue** [comment]
> However, respectfully, and without trying to be needlessly pedantic, the spec doesn't appear to say that. As far as I can tell, the spec only talks about the patch number in relation to bugs. Please correct me if I'm wrong.

Nope! I don't think you are wrong. But then, that is true of so many other things the spec does not say explicitly. Another thing that is true:

The spec says pretty much all that it has to say, for a thoughtful engineer, to be able to resolve those things on their own. Ya, many of us lack the confidence in our interpretations, but then we have this huge body of issues, discussing virtually all of those unsaid things.

If the spec tried to say everything, it would say nothing at all, because it would be virtually useless.

**Comment by openjck** [comment]
I hear that, and it makes sense. I also agree with your advice that _everything else_ (everything other than API changes and backwards-compatible features) can be a patch release (e.g., 1.0.0 -> 1.0.1), or an engineer can choose _not_ to release those things until something more important needs to be released.

Given that advice, I'm comfortable with semver locking this comment thread. I don't think there's likely to be much more productive discussion here, and we've come to a reasonable (and imperfect, like everything) resolution.

**Comment by jwdonahue** [comment]
@haacked (good to hear from you again):

> If it's a rare "pure" refactoring and no behavior has changed, not even bug fixes, then what's the point of releasing it? Releasing it is a collective inconvenience to all the package consumers who will be told that there's a new version of the package only to discover there's no bug fixes.

An excellent point, but there are cases where code smells, lead to refactoring. While not every stinky bit of code causes noticeable defects to most customers, it can be argued that a well run organization, can justify a refactor release, particularly if it's the refactor, the day before the code is put into maintenance or retirement mode.
