### ISSUE TITLE
Pre-release specification should not allow leading/repeated/trailing/individuals hyphens in identifiers

### ISSUE THREAD

**Issue by jessewebb** [semver/semver#147]
According to the SemVer 2.0.0 spec (point # 9):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

This does not restrict the usage of the '-' (hyphen) character in string (non-numeric) identifier parts. Therefor, the following are valid versions with pre-release parts:
- 1.0.0-alpha.-
- 1.0.0--
- 1.0.0----
- 1.0.0-123.---.-
- 1.0.0-123.ab--cd

The spec for the pre-release portion includes the clause that "Numeric identifiers MUST NOT include leading zeroes". I would suggest that a similar stance is taken on the hyphen character. IMO, only individual hyphens should be allowed in between other alphanumeric characters. Following this, all of the above versions would be invalid. Here are some examples of valid versions which follow this suggested constraint:
- 1.0.0-alpha.a-5
- 1.0.0-0-1
- 1.0.0-rc-1.2-34
- 1.0.0-a-l-p-h-a.1-2-3

**Comment by jwdonahue** [comment]
@jessewebb, unless you intend to pursue this further, please close at your earliest possible convenience.

**Comment by silkentrance** [comment]
@jessewebb Simple common sense. If you want it ugly and faeces like, be yourself both host and guest.

While we, the rationale, sniff and leak on it, moving forward.

Outdated, please close.
