### ISSUE TITLE
SemVer case study

### ISSUE THREAD

**Issue by bessarabov** [semver/semver#159]
I'm using SemVer in my library. I'm not sure that I did one thing correct, so I want to ask a question if what I did is best SemVer practice, or I could handle this situation better.

I have a library (if you are interested, here is the [link](https://metacpan.org/module/Weightbot::API)) that works with some https site. I give that library login and password and it returns some structured data. Everything worked ok.

But one day the library stopped working. I made some investigations and found out that there is the problem with SSL certificate of the site. The certificate has expired and my library throwed exeption and did noting. I have created the bug report for the site owners and I have fixed my library (so it worked with incorrect SSL certificate) and released new version with the change of the MINOR version level.

Some time passed and the site owners has fixed the SSL bug. I have updated my library so it checks that the certificate is correct. I've released new version of the library with change in MINOR version level.

Have I done everything correct? Is it what SemVer recomends do in such situations? Is right that i have changed the MINOR level? Or maybe I should handle this situation in some other way?

**Comment by jwdonahue** [comment]
@bessarabov , if your question has been answered and you have nothing further to add here, please close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@bessarabov, can you please close this thread? We're trying to eliminate open threads that have been answered and are unlikely to result in pull-requests.  Thank you.
