### ISSUE TITLE
Please add HTML IDs to the semver spec so that particular points can be referenced via URI fragments

### ISSUE THREAD

**Issue by binki** [semver/semver#164]
If I want to refer directly to point number 10 in the [2.0.0 specification](http://semver.org/spec/v2.0.0.html), I must use human language. If I could directly reference, via a relatively stable fragment identifier like `#semver-buildmetadata`, that particular point, that would reduce the amount of human work and potential for human error in referencing the spec.

**Comment by eed3si9n** [comment]
+1

**Comment by crazedsanity** [comment]
+1

**Comment by rfdrake** [comment]
This was brought up again in issue #222 and semver.org/#27 merged with https://github.com/mojombo/semver.org/commit/2af9fc3d40ac71cbb2c747d47241ccf46c8db9be

**Comment by jwdonahue** [comment]
@binki, Id's have been added, along with link symbols when you mouse over the section numbers. Please close this issue at your earliest possible convenience.  Thank you.

**Comment by jwdonahue** [comment]
@binki, can you please close this issue?  It has been resolved with a merge.  All of the numbered spec and FAQ questions have been given Id's.

**Comment by binki** [comment]
@jwdonahue Looks good. Sorry for forgetting about this.
