### ISSUE TITLE
Define strict ordering rules on prerelease version names

### ISSUE THREAD

**Issue by TimLovellSmith** [semver/semver#165]
Xavier Decoster notes (http://msdn.microsoft.com/en-us/magazine/jj851071.aspx
)

"For prerelease packages, the reason for not using a fourth build number is simple: NuGet doesn’t support build numbers in prereleases. You can’t create a NuGet package in the format major.minor.patch-prerelease.build or major.minor.patch-prerelease+build. Any other attempt to auto-increment a prerelease package using a build number will most likely fail because **the version precedence algorithm is sorting prerelease tags in alphabetical order**. This effectively means, for example, that v1.0.0-alpha2> v1.0.0-alpha10> v1.0.0-alpha02 (which brings me to the next rule, as you’ll see in a bit)."

I think it would be great if nuget understood that alpha10 or alpha-10 or alpha.10 is greater than alpha02 (etc.).

I would like to suggest that for semver3

'A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.'

Be amended to note:

Identifiers are treated as separate numeric and non-numeric parts when they contain both types of characters. Numeric parts MUST NOT contain leading zeros. 

Precedence ordering is alphabetic (lexicographic) for non-numeric parts, and numeric for numeric parts. And numerically named parts will precede non-numeric.
e.g.:
1.0.0-alpha <
1.0.0-alpha1 <
1.0.0-alpha2 <
...
< 1.0.0-alpha10
< 1.0.0-alpha10.1
< 1.0.0-alpha10.x
< 1.0.0-alpha10.x1

And recommend: numeric parts SHOULD appear once per identifier and only at the end of the identifier.

**Comment by jwdonahue** [comment]
@TimLovellSmith, I don't believe there is much chance of a change being taken on this one. Unless you intend to issue PR or have questions, please close this issue at your earliest possible convenience.
