### ISSUE TITLE
Regular Expression to match versions

### ISSUE THREAD

**Issue by joshuadgoldstein** [semver/semver#167]
It might be nice to include a regular expression which matches your versioning scheme as a sort of "example implementation".

**Comment by jwdonahue** [comment]
@joshuadgoldstein, see PR #460. This issue was addressed in other threads and and PR is pending to resolve the issue.  Unless you have questions or intend to issue an additional PR, please close this issue at your earliest possible convenience.  Thank you.

**Comment by steveklabnik** [comment]
Yes, closing this in favor of the duplicate issue/PR. Thank you!
