### ISSUE TITLE
Need instructions on libraries that track another library.

### ISSUE THREAD

**Issue by bf4** [semver/semver#169]
If the [yui-rails](https://github.com/nextmat/yui-rails) gem upgrades the yui3 library from version 3.10.3 to 3.13.0, but no yui-rails code has changed, I think the semantics should be

``` ruby
YUI_VERSION = '3.13.0'
VERSION =  "#{YUI_VERSION}.0.3.0"
```

where [0.3.0 is the 'yui-rails' version that follows semver independent of the YUI_VERSION](https://github.com/nextmat/yui-rails/commit/91ceca1953e9ebf69424a389abc784eb91f6ee18).

**Comment by jwdonahue** [comment]
@bf4 

Have you any further questions in regard to this issue? Any proposed changes to the SemVer spec? If not, then please close this issue at your earliest possible convenience.

**Comment by bf4** [comment]
@jwdonahue The issue doesn't appear to be resolved, IMHO.  I'll let a maintainer weigh in.

I do think that since posting this, the direction has been to directly track major version numbers, or some such.

**Comment by jwdonahue** [comment]
@bf4, neither @mojombo or @Haacked have weighed-in over the past four years, but you might get lucky.

Looking closer at your proposal, I don't believe it conforms to SemVer, as you seem to be building a compound version number that looks something like 3.13.0.0.3.0.  Did I read that correctly?

**Comment by jwdonahue** [comment]
@bf4, your problem is all about transient dependencies yes? A depends on B, B gets a version bump, what should happen to A?  Is that correct?

**Comment by bf4** [comment]
@jwdonahue yes, specifically in the case where A is a kind of domain-specific-adapter for B.  So, if I want to add B to my app, I use A, which bundles B.  This is more common now than when I first asked the question. e.g. https://github.com/jruby/activerecord-jdbc-adapter#activerecord-jdbc-adapter now tracks Rails 5.0.x as 50.x

**Comment by jwdonahue** [comment]
@bf4, how transient dependencies are tracked is a matter for tooling, not semver. Semver provides a standard means for labeling nodes in a dependency graph, not how to mange the entire graph. Unless you intend to issue PR related to this thread, please close it at your earliest possible convenience.

**Comment by bf4** [comment]
Sounds like that would be the pr

**Comment by jwdonahue** [comment]
The list of things the spec is not intended to cover would be too long for publication.

**Comment by bf4** [comment]
Closing as intentionally 'undefined' behavior
