### ISSUE TITLE
Semantic Versioning added to gitver

### ISSUE THREAD

**Issue by manuelbua** [semver/semver#173]
I added support for custom string formats in my little tool [gitver](https://github.com/manuelbua/gitver), so now Semantic Versioning is possible as well: i'm looking for testers and opinions, would you mind helping test it?

Gitver is a very simple, lightweight, tag-based version string manager for git, written in Python: it generates version strings by using Python-based formatting rules coupled with repository information, augmented by user-defined data.

Thanks in advance!

PS: i know this isn't the best place to ask, but this is the best place to find knowledgable programmers on the subject.

**Comment by jwdonahue** [comment]
@manuelbua, according to your readme.md file, gitver expects tags of the form [v]X.Y.Z[.REVISION][-PRE-RELEASE-METADATA], which is not actually SemVer compliant.  This a very old issue which nobody has responded to until now, please close it at your earliest possible convenience.

**Comment by manuelbua** [comment]
Hi @jwdonahue, thanks for taking the time for giving some feedback.
Yes, the input gitver expects are variations of that format, but what i meant when i said it support SemVer is that it can actually **produce SemVer-compliant output**, not that it also accepts tag in that format, that wasn't a goal either.

**Comment by jwdonahue** [comment]
@manuelbua, can you please close this issue, it's been three years, there's no SemVer related question to answer and no actions to be taken on the spec.
