### ISSUE TITLE
Time information

### ISSUE THREAD

**Issue by nikkas** [semver/semver#175]
Problem:
  Time information is important information which is missing from the semantic-versioning method.
New:
  v2014.02.17-2.0.0
Solution:
  The reader see the time of publication, understands the speed of evolution of the software, relates it with other events happened the same time, orders the versions easily etc...

**Comment by synagonism** [comment]
Revision.2017-02-12

name.m-m-p.yyyy-mm-dd

@zafarkhaja This way we express the SemVer goal of backward compatibility AND we express the time past between the changes to understand the general environment of changes.
example: http://synagonism.net/hitp/#idMeta
synagonism (= nikkas)

**Comment by zafarkhaja** [comment]
@synagonism so, if I didn't miss anything, you use this format to version web pages, that is you use it to number content revisions? Then I'm not sure I understand what backward [in]compatibility means in this context. Perhaps SemVer is just not what you need for this. Perhaps it's better to invent a different versioning system to accommodate your specific needs. 

On the other hand, SemVer could be the right tool to version HITP.

**Comment by jwdonahue** [comment]
@nikkas, it doesn't appear to be very likely that this idea will ever be adopted. Unless you intend to actively pursue this issue, please close it at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@Haacked, time close this issue.

**Comment by jwdonahue** [comment]
@nikkas, time data can be embedded in the build meta tag or package name. Also see [VersionMeta](https://versionmeta.org) and [VersionSchema](http://versionschema.org) for an alternative scheme that could include time stamps.

Unless you intend to issue PR for this, please close this issue at your earliest possible convenience.  Thank you.

**Comment by ukanuk** [comment]
Does format `x.y.YYYYMMDD` already match Semver 2.0.0? I see nothing in spec about incrementing versions _by one_, it just says to increment according to incompatible changes/compatible new features/bugfixes. I suggest `YYYYMMDD` since that's ISO date format and ensures the patch number always increases.
