### ISSUE TITLE
"[Pre-release] Numeric identifiers MUST NOT include leading zeroes"

### ISSUE THREAD

**Issue by damianpowell** [semver/semver#181]
I can read this two ways:
1. A pre-release identifier which consists entirely of decimal digits, MUST begin with a digit other than zero, or it MUST be the single digit zero, or,
2. A pre-release identifier which consists entirely of decimal digits, but begins with a zero, MUST be considered to be alphanumeric.

The distinction is important because it changes how we validate a SemVer string. Under the first approach, we would consider 1.2.3-alpha.012.2 to be invalid, but under the second approach, we would not. However, the sorting applied in approach 2 would consider the second identifier "012" to be an alphanumeric string.

Which is the correct approach, please?

**Comment by FichteFoll** [comment]
\*push\*

This is still an issue with the spec as it's unclear in this regard.

**Comment by mkllnk** [comment]
Just got confused about this as well. You could include a negative example to clarify this.

**Comment by FichteFoll** [comment]
Revisiting this again.

> 9) [...] Numeric identifiers MUST NOT include leading zeroes. [...]
> 11) [...]  identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. [...]

Following the points 9. and 11., the spec seems to indicate that only identifiers with a letter or a hyphen are considered alphanumeric identifiers, leaving numeric identifiers to consist only of numbers. Since 9. prohibits usage of leading zeroes, they are not valid numeric identifiers, thus declaring `1.0.1-alpha.012` not to be a semantic version.

Case closed, I suppose.

**Comment by jwdonahue** [comment]
@damianpowell, if you have no further questions regarding this issue, please close it at your earliest possible convenience.

**Comment by thrnio** [comment]
Rule 9 should probably explicitly state that a numeric identifier is an identifier which consists of only digits, similar to how rule 10 is explicit about it, since rule 9 comes first.

**Comment by jwdonahue** [comment]
@damianpowell, unless you intend to issue a PR or have further questions, please close this issue at your earliest possible convenience.

Thank you.

**Comment by alexandrtovmach** [comment]
👻 👻 👻 
Closed as staled
