### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by flyboarder** [semver/semver#185]
A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

This section has a false example... 1.0.0-0.3.7 has a leading zero, which is explicitly said it shouldn't contain. Or am I misreading this section?

**Comment by jwdonahue** [comment]
@flyboarder, if you have no further questions, please close this issue at your earliest possible convenience.
