### ISSUE TITLE
Turn FAQ headers into anchors

### ISSUE THREAD

**Issue by xavierdecoster** [semver/semver#187]
Often you want to point someone to the answer of one of the Frequently Asked Questions. Being able to send them a link to the question/answer could facilitate this a lot!

**Comment by jwdonahue** [comment]
@xavierdecoster, this addition seems to be included at https://semver.org/.  Not sure who did it or when it got done.  Unless you have further questions or additional information to add to this request, please close this issue at your earliest possible convenience.

Thank you.

**Comment by steveklabnik** [comment]
This works today. If there's still bugs, please report them over at https://github.com/semver/semver.org, thank you!
