### ISSUE TITLE
Define "package"

### ISSUE THREAD

**Issue by ecki** [semver/semver#189]
In the Java and OSGi world "package" is a term with a specific meaning. (And especially in OSGi you could even have a version number on seperate packages inside a bundle). I would therefore recommend you define that with package you actually mean "deliverable" or "deploymet unit" and not "java package". Or you define that the granularity at which you apply the version number might be on "API", "(osgi) package", "packages", "operation" or "deployment unit" or "application" level.

**Comment by jwdonahue** [comment]
@ecki, I have always assumed that when a specification does not provide its own definition of a word, the "standard dictionary" for the language the spec is written in, provides the definition.  In this case try looking at http://www.dictionary.com/browse/package?s=t and assume the SemVer spec intended a liberal application of those definitions, or to quote @mojombo's own words from the introduction:

> I call this system "Semantic Versioning." Under this scheme, version numbers and the way they change convey meaning about the underlying code and what has been modified from one version to the next.

Unless you have further questions or wish to issue a PR, please close this issue at your earliest possible convenience.

**Comment by ecki** [comment]
I dont agree that the dictionary link helps. Especially not since the **programming language** the spec applies to does define `package` differently. But sure I can open a pull request.

**Comment by jwdonahue** [comment]
Now that's are a really good start! I think you should issue a PR to semver/semver.

@Haacked (FYI).

**Comment by ecki** [comment]
Looks like I am the only one struggling with the definition.
