### ISSUE TITLE
Super versions

### ISSUE THREAD

**Issue by brettz9** [semver/semver#191]
Hi,

Hopefully my idea is not coming too late here, but here goes...

I think that there is a compelling reason to support a "super" version _prepended_ to  the "version core" which conveys a more arbitrary but still somewhat meaningful grouping of "newness". This super version could perhaps in some cases be effectively ignored, but still give some meaningful sense to users.

The super version could reserve "0" to mean that the project is not (yet) meant to be consumed by the wider public. This may coincide with an unstable API as per a major version == 0 , but not necessarily, e.g., where the API is stable but the feature set is either too bare to be useful or is inadequate in level of testing for the organization to wish to freely associate itself with the budding project or experiment. Conversely, a product deemed polished enough to be publicly released and invite feedback but not yet with a stable API might use super version "1" with a major version of "0" (though a super version of "1" would in most cases probably coincide with a major version of at least "1").

A new super version may or may not map perfectly with new builds, and even where it does, a super version would be more convenient for reference than say forcing users to refer to the timestamp--even while a project might still find it useful to mark the meta-data of its builds with timestamps).

**After 0, increments to the super version would simply indicate that the release was significant in some manner--whether or not backward-breaking changes have occurred.** Projects might also associate a super version with distinct support (e.g., determining, by incrementing, that a snapshot was being made prior to which no new modifications would any longer be added).

Distinction might be made on whether the version core may be reset. When a new super version is created and the project wishes to reset the version core to 1.0.0 or 0.0.0, the super version might be followed by a ".". As with major or minor version changes causing the minor or patch version to increment, the super version joined in this manner conveys the sense that the major, minor, and patch versions will be reset. Conversely, if the project wishes to merely continue incrementing the version core components, and continue, for example, to give a clear picture of how many backward-breaking changes have occurred (by the preservation of the major version), the super version might instead be separated from the version core by a "-".

_Usage scenarios_
1. After its public release at 1.1.0.0, a project makes 5 new backward-breaking changes but does not consider that these changes really indicate anything pioneering enough to justify a super version increase. The version after these changes might end up as 1.6.0.0
2. After a public release at 1.1.0.0, a number of minor modifications have been added, leading to version 1.1.35.0, but deemed to be of a significant enough nature to merit an increment to the super version. Thus, instead of staying at 1.1.35.0, the project might release as 2.1.0.0. or 2-1.35.0.

While I know this is "semantic" versioning after all, besides carrying some semantic meaning of its own, a super version is, I believe, a very practical need along the lines of, but distinct from, the type of information conveyed by post-version meta-data.

**Comment by jwdonahue** [comment]
@brettz9, it does not appear that any changes to the SemVer spec are required here. You are free to pre/post-pend anything you like to the version string, provided you supply white space between your non-conforming bits and the SemVer bits.  

There is considerable resistance to adding additional fields to version triplet, and it very unlikely that your proposal will be accepted.  Please close this issue at your earliest possible convenience.

**Comment by brettz9** [comment]
If there is considerable resistance, then let it be expressed here as you have done. The owner is welcome to close the issue, but I'd otherwise like for it to be available for discussion.

(FWIW, I'd also like to see an alternative syntax which may be even less likely to be adopted but which I also feel would be practical: making the major, minor and patch versions independent such that `1.3.5` could progress directly to `1.4.5` (or even `2.3.5` or `2.4.5`) with the practical effect that one trusting the issuers of the semver would be confident that the new major and minor version (telegraphing breaking changes and new features respectively) did not signify any fixes in bugs, and thus people could avoid an update if they were concerned about bugs only. While some go through the trouble of continuing to support older versions and making patches for them, for those projects which don't do so, it would help to at least have semantic numbering which actually makes clear whether a minor version change also includes bug fixes or not.)

**Comment by jwdonahue** [comment]
Ya, I think we could describe a kind of version meta string that is independent of SemVer and other versioning schemes, which could be used to link to a version schema that provided exactly the kind of information you want to know about that specific version number.  For instance, whether the developers follow a fix-bugs first policy and then add features, or if they mix them all in together.  The goal would be to provide enough information that automation could easily and safely map between different kinds of version strings.  Kind of an ISO-9xxx Super-Light.

**Comment by jwdonahue** [comment]
@brettz9 , FYI: [VersionMeta](https://versionmeta.org) and [VersionSchema](http//versionschema.org).

**Comment by brettz9** [comment]
Great, look forward to trying to get a closer look... The http://versionschema.org/  link is broken though which you may want to fix for any others coming here (and I can remove this comment)...

**Comment by jwdonahue** [comment]
@brettz9, fixed. Thanks.

**Comment by alexandrtovmach** [comment]
👻 👻 👻 
Closed as staled
