### ISSUE TITLE
EBNF grammar

### ISSUE THREAD

**Issue by christianhujer** [semver/semver#192]
The Semantic Versioning Spec could have an EBNF grammar.

Here it is, according to http://www.w3.org/TR/xml/#sec-notation.

version ::= MAJOR '.' MINOR '.' PATCH ('-' PRE)? ('+' BUILD)?
MAJOR ::= decimalnumber
MINOR ::= decimalnumber
PATCH ::= decimalnumber
PRE ::= string
BUILD ::= string
string ::= [0-9A-Za-z-]+
decimalnumber ::= [0-9]+

**Comment by gvlx** [comment]
[Here it is](https://github.com/semver/semver.org/issues/59#issuecomment-393560776).

Please comment and correct.

**Comment by glebec** [comment]
@gvlx my corrections:

- `PreReleaseIdentifier` had a spurious `+` on `NumericIdentifier`
- `AlphaNumericIdentifier` cannot parse as `IdentifierCharacter* NonNumericCharacter ...` b/c `IdentifierCharacter*` includes `NonNumericCharacter`. So a typical parser would consume all of `the input using `IdentifierCharacter*` and then fail because there is no `NonNumericCharacter` to consume. The correct version is `NumericCharacter* NonNumericCharacter ...`.

```ebnf
Version ::= VersionCore ('-' PreRelease)? ('+' Build)?

VersionCore ::= Major '.' Minor '.' Patch
Major ::= NumericIdentifier  
Minor ::= NumericIdentifier  
Patch ::= NumericIdentifier  
PreRelease ::= CompoundPreReleaseIdentifier 
Build      ::= CompoundBuildIdentifier 

CompoundPreReleaseIdentifier ::= PreReleaseIdentifier ('.' PreReleaseIdentifier)*
CompoundBuildIdentifier      ::= BuildIdentifier      ('.' BuildIdentifier)*

PreReleaseIdentifier     ::= AlphaNumericIdentifier | NumericIdentifier
BuildIdentifier          ::= IdentifierCharacter+

NumericIdentifier        ::= '0' | ( PositiveNumeric NumericCharacter* )
AlphaNumericIdentifier   ::= NumericCharacter* NonNumericCharacter IdentifierCharacter*

IdentifierCharacter ::= NonNumericCharacter | NumericCharacter

NonNumericCharacter ::= [A-Za-z-]
NumericCharacter    ::= '0' | PositiveNumeric
PositiveNumeric     ::= [1-9]
```

**Comment by gvlx** [comment]
The EBNF has been corrected by @glebec on https://github.com/semver/semver/issues/192#issuecomment-426123552 .

This issue should now be closed.

**Comment by jwdonahue** [comment]
@christianhujer , unless you have further questions, can you please close this issue at your earliest possible convenience?

**Comment by ebkalderon** [comment]
@christianhujer Looks like the EBNF grammar has already been merged into `master`. Can this issue be closed?
