### ISSUE TITLE
Definition of "stable"

### ISSUE THREAD

**Issue by RWOverdijk** [semver/semver#211]
Hello community!

I'm going to toss in my opinion on something, and will probably see some pushing back. I disagree on the way "stable" is being described:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

And

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0.

Besides the obvious grammatical error _(you should be 1.0.0)_, I believe this to be false information. As stated at the top of the document:

> MAJOR version when you make incompatible API changes,

This implies that 0.1.0 could be considered stable. You start off at 0, and as long as you don't change the initial API, there's no need to bump a major version. Not even when making the API public, because that's not an incompatible API change.

It **is** true that almost nobody gets it right on the first try, and they'll most likely mess something up, causing a major version bump, but this means that they were public and stable to begin with. In reality, any tag must be considered as stable. Until it is, it's either a branch, alpha, beta or RC.

So I suggest either changing the MAJOR version rule, or the stable rule into something less restrictive.

Please don't kill me. :)

**Comment by jwdonahue** [comment]
@RWOverdijk, it has been my experience that in most cases, my customers have come knocking on my door wanting me declare a 1.0.0 version so they can also do that.  It's essentially, a milestone marker plus a promise not to break anything in the future without bumping major again, or adding a prerelease tag.  As long as your customers are willing to go along with your dwelling in the 0.x.x ranges, you are absolutely free to do so, but you should also be aware that 0.x.x transmits the idea that literally anything could change on the next patch bump.

Unless you have further questions, please close this issue at your earliest possible convenience.

**Comment by RWOverdijk** [comment]
Yeah, I still use it as intended. I the first push of code doesn't have BC breaks I don't bump to 1. So far that has worked fine. So I'll close this.
