### ISSUE TITLE
HTML meta tag "version"

### ISSUE THREAD

**Issue by dvorapa** [semver/semver#217]
Hello there, we are a small movement from the Czech Republic (somewhere in the middle of the Europe) and our goal is to make an enhancement to the HTML5 spec. We are preparing the specification for new meta name extension called `version`. And we are looking for anybody interested in our project, who wants to help us with the proposal of meta name version spec. Here is an example of the valid meta tag:

```
<meta name="version" content="0.1.0+1">
```

Name could be case-insensitive, but content should strictly use @mojombo's semver. What do you think about it?

See https://github.com/dvorapa/meta-version for documentation and specification. If there is anything wrong, please fill in a new issue.

**Comment by jwdonahue** [comment]
@dvorapa, unless you have questions regarding SemVer or intend to submit a PR request related to this issue, please close it at your earliest possible convenience.
