### ISSUE TITLE
Page anchors for all paragraphs please..

### ISSUE THREAD

**Issue by tomByrer** [semver/semver#222]
I wind up referencing SemVer.org on average every month.  Would be great that we could link directly to a paragraph instead of having to quote the entire block, so in code comments we can do:
`/* spec formatting: http://semver.org/spec/v2.0.0.html#pre-release */`

Likely the best bet to change the paragraph numbers to `<h4>` or the like.  Let me know if you want a PR example.

**Comment by NewAlexandria** [comment]
I've created a PR to solve this.  [Demo on my fork](https://github.com/NewAlexandria/semver/blob/master/semver.md#faq-5)

**Comment by adjohnson916** [comment]
Relates to https://github.com/mojombo/semver.org/issues/27.

**Comment by jwdonahue** [comment]
I like this.  It seems to have been partially implemented already.  I'd like to see visible anchor indicators around or underlining every paragraph number or directly above/next-to every non-numbered paragraph.

**Comment by steveklabnik** [comment]
This is pretty much implemented. If there's still stuff missing, please open issues over at https://github.com/semver/semver.org. Thanks.

**Comment by NewAlexandria** [comment]
Yup, been up for a while, but thanks for grooming the repo issues 👍
