### ISSUE TITLE
Add #EOL

### ISSUE THREAD

**Issue by franz-josef-kaiser** [semver/semver#223]
Always when there is a discussion about upgrading or not (like the ones you know about PHP versions and WordPress), there's somehow no really strong argument that the people accept. So I [propose a more "in-your-face" approach](https://twitter.com/unserkaiser/status/514380418360283136) and clearly indicate when a version will get no more support:

> 1.0.0-alpha
> 1.0.0-alpha.1
> 1.0.0-beta
> 1.0.0-beta.1
> 1.0.0-rc.1
> 1.0.0-rc.2
> 1.0.0-rc.3
> 1.0.0
> 1.0.1
> 1.1.0
> 1.1.1
> 1.1-EOL

This would clearly indicate that _no one should use this version anymore_ and that there won't be any more support for that version.

Let's face it: If we have three different types of _this is not ready_ suffix for a version, there can at least be one _this is dead_ suffix.

**Comment by jwdonahue** [comment]
@kraftner, yes, bump the patch level and attach the appropriate EOL meta tag as @FichteFoll [suggested](https://github.com/semver/semver/issues/223#issuecomment-56538560).

**Comment by jwdonahue** [comment]
@franz-josef-kaiser, your proposal would be a breaking change and has a non-breaking work-around as specified by [@FichteFoll](https://github.com/semver/semver/issues/223#issuecomment-56538560). Unless you intend to produce a PR linked to this issue or have further relevant comments, please close this issue at your earliest possible convenience.
