### ISSUE TITLE
Update to cover platform applications

### ISSUE THREAD

**Issue by kramos** [semver/semver#224]
If you treat your whole platform as an application (as PaaS providers do / PaaS applications let you do), I'd like to propose alternative definitions:
- MAJOR version when you expect consuming Business Applications to need changes e.g. you change the RDMS
- MINOR version when you don’t expect consuming Business Applications to break, but need full regression testing, e.g. configuration tuning or a security patch
- PATCH version when you make backwards-compatible changes expected to have no or a very low change of external impact.  For example if the IaaS API has a change which the Platform Application fully abstracts Business Applications from.

Please see here for more context:
http://markosrendell.wordpress.com/2014/08/15/so-if-we-are-treating-our-platform-as-an-application-paaa-what-should-it-do/

**Comment by jwdonahue** [comment]
@kramos, how you map SemVer to your particular domain is beyond the scope of SemVer. If you are asking us whether your suggestion matches up with the spirit and intent of SemVer, I think it might.

Unless you have further comments/questions or intend to issue PR against this issue, please close it at your earliest possible convenience.
