### ISSUE TITLE
Defining version skipping

### ISSUE THREAD

**Issue by icylace** [semver/semver#233]
I was just reading a [post](http://wildermuth.com/2014/10/29/It_Is_Too_Soon_to_Panic_on_AngularJS_2_0) about the recent panic storm over the forthcoming AngularJS 2.0.  One of the comments caught my eye (unfortunately there's no direct link to the comment):

> i get that semantic versioning means a rev number can mean a breaking change, but complete incompatibilty isn't what people expect.

This got me thinking about the possibility of extending SemVer to be able to explicitly account for massive breaking changes when they occur.  For example, going from version 5.0.0 to 7.0.0 expresses a greater shift than going from 5.0.0 to 6.0.0.

I don't know how many things have jumped versions in the past but a couple examples off the top of my head would be Opera going [from version 12 to version 15](http://www.opera.com/docs/changelogs/mac/) and Winamp going [from version 3 to version 5](http://en.wikipedia.org/wiki/Winamp).  Granted marketing was likely a heavy influence in these version number jumps but the ability to communicate massive changes through version numbering progression fits well with what SemVer was made for.

This concept can also be applied to the minor and patch version numbers.  Skips in minor versions could mean that lots of new backwards-compatible functionality has been added.  Skips in patch versions could mean that lots of fixes were made.

There are a couple drawbacks for my proposal that I'm still struggling with.  The first drawback I see is the vagueness for what would be considered large enough changes to merit version skipping.  The second drawback would be the potential overuse of version skipping.  However, I think it's possible to address both issues well enough to be able to make version skipping a useful addition to SemVer.

**Comment by AloisMahdal** [comment]
How is that ambiguous?

And how would unambiguously you define "breaking change"?  Renaming the only function the API ever had? Of course, but what about removing one of 100? What about changing an embedded signing key?  What about ... just bumping the version number and nothing else?

If I bump major version, I'm sending a very clear message: that this and next version *may* break software that depend on it but this dependency may mean something else for different software.  If for example I remove function, I'm obviously breaking those that use it, but not necessarily those that don't. (But still may break their future plans to use it.) What I'm trying to say that there's no way to quantify the amount of changes: "zero or more" is all you can really safely say.  Point of semver is to be able to pass the "or more part" of the message.

Introducing zero significant changes is just a corner case of "zero or more".

Of course, it would be totally irresponsible of the developer to bump major version every day as that would probably annoy the hell out of their users.  But other than that, there's no real difference between bumping (once a few years) from 1.x.y to 2.x.y or from 1.x.y to 100.x.y.  There's no real harm in it.

**Comment by curiousinternals** [comment]
As far as I understand it, SemVer is meant to communicate what type of changes have occurred, not 'how much' change has occurred. If a user wants to know the details of how much has changed, they should look at the changelog. A long changelog tells them it's a big update.

Also, I don't see a practical use to knowing that a change is 'big'. If a change is breaking, big or small, I'd still need to read up on exactly what has changed to know how it affects me.

**Comment by Haacked** [comment]
> As far as I understand it, SemVer is meant to communicate what type of changes have occurred, not 'how much' change has occurred. If a user wants to know the details of how much has changed, they should look at the changelog. A long changelog tells them it's a big update.

:sparkles: Exactly.

Though the way I usually phrase it, it's more about communicating the intent of the change and the likelihood of the changes breaking you.

After all, _every_ change has the potential to be a breaking change. Someone could be doing something risky like relying on private internals of your code for example or the file size of your binary.

But in those cases, they signed up for the risk and they deserve whatever befalls them. :smile: The goal of Semver is to help communicate "Yeah, this has a high probability of breaking you." or "This should be safe to upgrade to unless you're doing something risky."

**Comment by jwdonahue** [comment]
@icylace, unless you have further questions or concerns, please close this issue at your earliest possible convenience.

**Comment by icylace** [comment]
@jwdonahue Apologizes for keeping this issue open with no response for so long.  I'm closing it now because upon reflection I agree that the changes I originally proposed are not worth it.
