### ISSUE TITLE
When should or shouldn't a version number have a 'v' at the beginning?

### ISSUE THREAD

**Issue by RyPeck** [semver/semver#235]
At the top of the document all the version have a 'v' character in the front. I'm curious why this is, when it should and shouldn't occur.

```
v2.0.0 v2.0.0-rc.2 v2.0.0-rc.1 v1.0.0 v1.0.0-beta
```

It's a weird appearance that isn't mentioned anywhere in the documented. If I have a list of version and some of them have the v in front and some don't it will be some odd inconsistencies when it comes to sorting. Thoughts/Comments?

**Comment by silkentrance** [comment]
semver version numbers must not include redundant information such as a 'v' prefix. For git tags this is ok as it is a common best practice.

**Comment by steveklabnik** [comment]
The `v` has since been removed. Closing!

**Comment by bcope** [comment]
[Link to SemVer documentation that specifies this](https://semver.org/#is-v123-a-semantic-version).
