### ISSUE TITLE
API defintion?

### ISSUE THREAD

**Issue by FrankDMartinez** [semver/semver#236]
The website "semver.org" states:

> For this system to work, you first need to declare a public API. This may consist of documentation or be enforced by the code itself. Regardless, it is important that this API be clear and precise.

Exactly what qualifies as an "API"? Any function/method/procedure? Only specific ones?

**Comment by jwdonahue** [comment]
@FrankDMartinez, unless you have further questions, please close this issue at your earliest possible convenience.
