### ISSUE TITLE
Which version is greater? beta or betas

### ISSUE THREAD

**Issue by hartungstenio** [semver/semver#239]
I was dealing with some implementations, and found a really weird case, which left me thinking:

Which version is greater? 1.0.0-beta or 1.0.0-betas
Both of them have the same amount of pre-release identifiers, but one is longer.
Which one of those is the newest version?

**Comment by DavidFichtmueller** [comment]
I think the rules are pretty clear on this one: 
1.0.0-beta < 1.0.0-betas
Rule 9: "A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers. [...]"
Rule 11: "[...] identifiers with letters or hyphens are compared lexically in ASCII sort order"

It would be really helpful to have a web app/web services/library that would do the ordering according to the rules, so one could check the ordering for questions like this.

**Comment by hartungstenio** [comment]
@DavidFichtmueller actually, I was creating exactly [that kind of library](https://bitbucket.org/chrishartung/semver-j/). It is more like a "Learn Java" thing, since I begun to work with Java just now. But it is a library capable of parsing and comparing versions (actually just parsing since I'm coding the comparison as I write this comment just now).

Just don't expect too much of it right now, since I'm still learning Java. It should be usable some time in the future.

**Comment by DavidFichtmueller** [comment]
Wow, cool thing. I guess this could be useful to a lot of people. And it is a great project to learn a programming language as well. Happy Coding!

**Comment by Computer-Whiz123** [comment]
@hartungstenio your link is broken...

**Comment by hartungstenio** [comment]
@Computer-Whiz123 sorry. I changed my BitBucket username. The current link is: https://bitbucket.org/hartungstenio/semver-j

**Comment by jwdonahue** [comment]
@hartungstenio, unless you have further questions or comments, please close this issue at your earliest possible convenience.
