### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by coreyavis** [semver/semver#245]
I didn't see any information on how nightly builds should be denoted.

**Comment by FichteFoll** [comment]
See discussion in #200 and similar issues.

**Comment by jwdonahue** [comment]
@coreyavis, I have managed to handle this several different ways over the years.  My best advice is to append a -prerelease tag of some kind on all nightly builds, plus a build metadata tag.  A common practice looks something like:

ProductName 0.0.<patch>-a.nightly+BranchName.MachineName.<commit hash>

Always bump the patch number and pin the major and minor numbers to zero. You can optionally encode version provenance in the BranchName or append two or three dot separated numbers to build meta-data.

Other options:

ProductName.BranchName.Nightly <semver string>
Nightly.BranchName.ProductName <semver string>

The point here is that night build processes are an internal thing and there would normally be an additional release step that selects a tested build, signs and packages it, so nightlies really aren't within the scope of the standard.  Just apply the standard to your processes in whatever ways seem most sane for you organization.

Unless you have any further questions, please close this issue at your earliest possible convenience.
