### ISSUE TITLE
Seperating structural and change semantics

### ISSUE THREAD

**Issue by EddieGarmon** [semver/semver#250]
The more I talk to people about SemVer, the more I explicitly separate the structural semantics from the change semantics.

I think that defining these concepts separately helps alleviate a lot of the pains on when to do what, and how to handle 0.Y.Z versions in a manner that adds the most value for downstream consumers.

How about something like the following?
## 
## Summary

A semantic version structurally has:
- A defined public API that it is representing.
- Three integer parts in the format X.Y.Z.
- When X is zero (0), the API should be considered volatile, but consumption is not discouraged. Once the API is generally stable, X should move from zero.
- Additional labels for pre-release and build metadata are available as extensions but are not part of the version proper.

When comparing two semantic version numbers, you can always tell what type of API change should be expected, which should be one of:
- Breaking, when any backwards incompatible changes are introduced to the public API.
  - if (X >= 1) then increment X and reset Y and Z to zero
  - if (X == 0) then increment Y and reset Z to zero
- Additive, when new, backwards compatible functionality is introduced to the public API.
  - if (X >= 1) then increment Y and reset Z to zero
  - if (X == 0) then increment Z 
- Repackaging, when backwards compatible bug fixes are introduced or the API is repackaged for distribution
  - if (X >= 1) then increment Z
  - if (X == 0) not allowed on volatile APIs

**Comment by Ericson2314** [comment]
The JSON RFC does a good job of this, introducing groups of non-terminals with a description of their semantic meaning.

**Comment by jwdonahue** [comment]
@EddieGarmon, that appears to be one state machine that is compliant with SemVer, but there are others as well. For instance, according the spec, you can have 0.0.0-n.  Unless you intend to issue a PR related to this issue or have further comments/questions, please close this issue at your earliest possible convenience.

**Comment by EddieGarmon** [comment]
This has not been addressed, why close?

**Comment by alexandrtovmach** [comment]
@EddieGarmon Thanks for reaching out 👍 Last comment was added 2 years ago, so it's kind of "staled", do you agree? 😄 

I'm just trying to clean-up current list of tasks from everything that's not actual anymore #573. I removed "staled" label, and will keep on this issue after urgent things

**Comment by alexandrtovmach** [comment]
>SemVer spec is something stable and strict, and if you want to change it, please create fork or start another project

closing in favor of https://github.com/semver/semver/issues/703#issuecomment-841420754
