### ISSUE TITLE
Fixed width version part alternative to spec.

### ISSUE THREAD

**Issue by travis-a-hoffman** [semver/semver#255]
Where I work, and for many, tomcat is used to serve up wars. Traditionally, wars are named: foo-max.min.build.war. Unfortunately, Tomcat does alphabetic comparison to evaluate when to replace a war. In this case, version foo-1.2.9.war is evaluated as being a version after foo-1.2.10.war, and thus tomcat won't automatically do the update.

The workaround we've found to be simplest and most inline with Semantic Versioning is to use fixed width fields, such as 1.02.0009, or 1.002.009 to delay (and make less likely) the decimal overflow of an individual field. It's not ideal, but it works for this situation. It would be nice to make this an optional or variation of the spec.

**Comment by FichteFoll** [comment]
Imo  this takes away some of the uniformity of semvers. A stricter standard is usually the better option unless flexibility is required by many. Most programming languages don't allow for numeric literals with leading zeros either. 

BTW, I thin this was explicitly added after  2.0.0-rc.2

**Comment by rlidwka** [comment]
I think semver should define the *meaning* of those numbers, not an actual format. So I would still consider `1.02.0009` a semver, and even `I.II.IX` is as long as release policy is appropriate.

**Comment by travis-a-hoffman** [comment]
Thanks for the feedback, I think I understand a bit more about semver. I might humbly suggest a clarifying note as an attachment to, but not part of, the spec explaining how to approach these sorts of variations while keeping with the spirit/vision of semver.

**Comment by FichteFoll** [comment]
@rlidwka unfortunately, that would complicate parsing a lot, and unnecessarily. Most people are using 0x30 to 0x39 as decimal digits anyway, and allowing leading zeroes raises the question whether `9` and `000009` are equal or unequal.

**Comment by jwdonahue** [comment]
@travis-a-hoffman, how you map SemVer strings to/from other formats is a tool design issue and out of scope for SemVer.  Unless you have further questions, comments or intend to issue a PR for this, please close this issue.

**Comment by alexandrtovmach** [comment]
👻 👻 👻 
Closed as staled
