### ISSUE TITLE
Some comments about semver

### ISSUE THREAD

**Issue by Vampire** [semver/semver#258]
I just read the spec at 255bc951da97e1642050d56170b969c702094f10 and I have some notes for you.
I hope it is ok to have them in one issue.
# Text
## Questionable versions

Here some examples of versions that are valid according to the spec, but I'm not 100% sure this is intended:

| Version | Comment |
| --- | --- |
| `1.0.0---+123` | is a valid version? There the pre-release identifier is "--" |
| `1.0.0-0.-.-.-+123` | is also a valid version with "0", "-", "-" and "-" as pre-release identifiers |
| `1.0.0-001foo` | should this be allowed? according to the text it is |
| `1.0.0-001-foo` | how about this? |
| `1.0.0+000001` | how about this? |
## Sorting

The spec describes what to compare when if comparing semvers and how to interpret it. But it is missing about case-sensitivity. I'd like to suggest adding that identifier comparison has to be done case-insensitively.
# BNF form
## Use EBNF

I'd like to suggest using EBNF according to ISO 14977 instead of a non-standard modified BNF like currently, it is much more readable and makes the result much more concise, e. g. by eliminating the need for recursion and introducing optionals.

E. g.

```
<pre-release> ::= <dot-separated pre-release identifiers>
<dot-separated pre-release identifiers> ::= <pre-release identifier> | <pre-release identifier> "." <dot-separated pre-release identifiers>
```

could be written as

```
pre_release = pre_release_identifier, { ".", pre_release_identifier };
```
## Reuse nonterminals where possible

```
<numeric identifier> ::= "0"
                       | <positive digit>
                       | <positive digit> <digits>
```

should be

```
<numeric identifier> ::= <digit>
                       | <positive digit> <digits>
```
## Simplify the BNF form, even if not using EBNF

e. g. if

```
<identifier characters> ::= <identifier character>
                          | <identifier character> <identifier characters>
```

is changed to

```
<identifier characters> ::= | <identifier character> <identifier characters>
```

you can simplify

```
<alphanumeric identifier> ::= <non-digit>
                            | <non-digit> <identifier characters>
                            | <identifier characters> <non-digit>
                            | <identifier characters> <non-digit> <identifier characters>
```

to

```
<alphanumeric identifier> ::= <identifier characters> <non-digit> <identifier characters>
```

as now `<identifier characters>` can be empty
# SVG

The pre-release and build parts can be simplified.
The part before and after the dot are identical in both cases.
So you can simply loop back to the beginning of the respective cluster start after the dots

**Comment by jwdonahue** [comment]
@Vampire 

## Questionable versions
All are expected to be legal SemVer strings.  Such string may result when automation finds empty data fields, or might even have some meaning to somebody. Disallowing them while retaining the usefulness of the current spec would just complicate the spec and make it harder to implement.

## Sorting
Case sensitivity has been covered in other issues, can't be changed in the 2.x.x series and there is no current initiative to get SemVer 3.x.x off the ground.

## BNF
Interesting points, please open a separate issue if you're willing to do the work and issue a PR.

## SVG
Same as for BNF, separate issue and present a PR.

In any case, please close this old issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@Vampire, unless you intend to issue a PR or have further questions, please close this issue at your earliest possible convenience.
