### ISSUE TITLE
How to use cocoapod for my existed  workspace and static library if static library would like to use cocoapod? 

### ISSUE THREAD

**Issue by wenrisheng** [semver/semver#269]
I new a project with workspace, like this:
-MyProj
--MyProj.xcodeproj
-MyStaticLibrary
--MyStaticLibrary.xcodeproj
-MyWorkspace.xcworkspace
-Podfile

then MyStaticLibrary and MyProj would use cocoapod, I dont know how to do it?
How I write the Podfile?
Have a demo?
Any can help me?

**Comment by jwdonahue** [comment]
@wenrisheng, please take your cocoapod questions to https://github.com/CocoaPods/CocoaPods and close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@wenrisheng, please close this thread. It has nothing to do with semver and is not going to lead to a PR.
