### ISSUE TITLE
Is 1.7.0.fc22 match the semver standard

### ISSUE THREAD

**Issue by haosdent** [semver/semver#271]
Hello, the docker version output in fedora is 

```
docker --version
Docker version 1.7.0.fc22, build 74e7a7a/1.7.0
```

Does this output match semver? Or only "1.7.0-fc22" match semver. Thank you in advance.

**Comment by FichteFoll** [comment]
I'm not gonna answer your question, but instead would like to know why you have this question in the first place? Which part exactly is unclear to you?

**Comment by haosdent** [comment]
Oh, I got it. Thank you

**Comment by somenxavier** [comment]
In general, is `x.y.z.t` a semantic version?

**Comment by haosdent** [comment]
not

**Comment by somenxavier** [comment]
Thanks. Just three numbers.

**Comment by jwdonahue** [comment]
@haosdent, unless you have further questions, please close this issue at your earliest possible convenience.
