### ISSUE TITLE
Can we have a consistent version number for Semantic Versioning?

### ISSUE THREAD

**Issue by HansOlsson** [semver/semver#274]
Due to another ticker I realized that the following two:
http://semver.org/
https://github.com/mojombo/semver/blob/master/semver.md
are both publicly available versions called "Semantic Versioning 2.0.0"- with slightly different contents (i.e. the latter is a "patched" version - removing an ambiguity and some minor spelling errors - similarly as one would release a new patch version to initialize a local variable).

Having two different versions of Semantic Versioning 2.0.0 with the same name and version makes it difficult to discuss which version of Semantic Versioning we are using.

The confusion is even more ironic considering that one of the changes was caused by a discussion about nightly builds, https://github.com/mojombo/semver/issues/200 , - and one could argue that https://github.com/mojombo/semver/blob/master/semver.md is a nightly build.

The logical solution would be rename the latter version to "Semantic Versioning 2.0.1",  "Semantic Versioning 2.0.1-Beta", "Semantic Versioning 2.0.1-Nightly-2015-09-16",  "Semantic Versioning 2.0.1-Nightly.2015.9.16", or something similar

**Comment by HansOlsson** [comment]
Note: 
This ticket is just about making it convenient to refer to the different versions (and leading by example).
The change is not formally required (as far as I can see), since Semantic Versioning does not state that its versions confirm to Semantic Versioning.

**Comment by jwdonahue** [comment]
@HansOlsson, the semver.org site has the standard.  There are probably dozens of exact copies and modified versions all over the net that we can do nothing about, but I do agree that [mojombo/semver](https://github.com/mojombo/semver/blob/master/semver.md), now [semver/semver](https://github.com/semver/semver/blob/master/semver.md), should either have an updated version in the title or it should just have a place holder until someone decides on what the next release version is and that new version would only be reflected on semver.org site.

**Comment by steveklabnik** [comment]
I believe this ticket was filed when the website was very different, as far as I can tell, this has been fixed. (And additionally would have been a good issue for the website repo, rather than this one.) Thank you!

**Comment by HansOlsson** [comment]
> I believe this ticket was filed when the website was very different, as far as I can tell, this has been fixed. (And additionally would have been a good issue for the website repo, rather than this one.) Thank you!

It is not fixed:

https://semver.org/#spec-item-10 says 
"Build metadata SHOULD be ignored when determining version precedence."

https://github.com/semver/semver/blob/master/semver.md says 
"Build metadata MUST be ignored when determining version precedence."

**Comment by klehelley** [comment]
I haven't made a complete diff of the content on the website and the content of the `v2.0.0` tag of the `semver/semver` project, but for your specific example I see no difference.

The version of the specification that can be found in `master`, that you are using to point out differences, is just a work in progress and not a final version; thus it should not be considered authoritative.

A new version of SemVer will eventually be released, considering some of the changes being discussed around here, though it will likely take time. That new version will include the change you are pointing out.

**Comment by HansOlsson** [comment]
> I haven't made a complete diff of the content on the website and the content of the v2.0.0 tag of the semver/semver project, but for your specific example I see no difference.
>
> The version of the specification that can be found in master, that you are using to point out differences, is just a work in progress and not a final version; thus it should not be considered authoritative.

The problem is that we cannot see this from the page itself - which says "2.0.0" not "3.0.0-Development"; and we are led to this main page by link.

Having a development version visible on GitHub is common for many projects - and it seems that the conclusion is that there is no need to update their version number until released.
