### ISSUE TITLE
Forward compatibility of persistent data

### ISSUE THREAD

**Issue by danielshahaf** [semver/semver#275]
[Subversion's release numbering scheme](https://subversion.apache.org/docs/community-guide/releasing#release-numbering) is approximately(?) semver, but [additionally](https://subversion.apache.org/docs/community-guide/releasing#release-compat) also allows to infer client-server compatibility and persistent-on-disk-data compatibility from the version numbers.  I wonder whether semver should be discussing either of those aspects.

For example, Subversion promises that release A.B.x will be able to read files created by release A.C.y if B ≥ C. In particular, A.B.x is promised to be forward compatible with any later A.B.y, so downgrades from A.B.y to the earlier A.B.x will be possible. Should semver be making a similar promise about forward compatibility? It would be relevant to any software that uses its own file format.

(I didn't find any discussion of forward compatibility in v2.0.0.)

**Comment by FichteFoll** [comment]
Yes, this is pretty much exactly what semver promises, except it's not explicit about file formats but anything that has a public interface. File formats would fall under that in most situations.

Alternatively you can versionify the file formats themselves, but incompatible changes should most likely also cause a major increase of the main application.

**Comment by danielshahaf** [comment]
Of course file formats are a form of API.  My point is that semver doesn't talk about forward compatibility at all: it does not promise that downgrading from 1.2.3 to 1.2.1 will be possible.

**Comment by FichteFoll** [comment]
I think it does. You are not allowed to add funtionality or break functionality (e.g. remove it) in a patch release.

**Comment by danielshahaf** [comment]
1.2.3 could upgrade the on-disk file to a format that 1.2.2 doesn't know how to read.

This would not be an API change or a new feature if the existence of the file is an implementation detail.

**Comment by jwdonahue** [comment]
@danielshahaf 

> Of course file formats are a form of API. My point is that semver doesn't talk about forward compatibility at all: it does not promise that downgrading from 1.2.3 to 1.2.1 will be possible.

It literally requires that 1.2.3 only has non-breaking bug-fixes, relative to 1.2.1, but it does not require that you can safely roll-back from 1.2.3 to 1.2.1.  In most cases you probably can, but any newer version could modify undocumented private data structures in order to fix those bugs, so it could require an uninstall followed by an install, and data loss could happen.  The spec is (rightfully) mute on roll-back capabilities.

Unless you have further questions, please close this issue at your earliest possible convenience.
