### ISSUE TITLE
How to versionize a fork? (including the original version number)

### ISSUE THREAD

**Issue by rugk** [semver/semver#278]
Abstracting https://github.com/rugk/threema-msgapi-sdk-php/issues/3...

We have:
- a original version, which will be developed and versions of it will be released
- a "community edition" of this version, which is based on the original version, but additional features or changes may be included
- a situation where the community version will still be updated with new official version releases by integrating them into the CE version.

That's why it would be good to have both version numbers - the "official one" and the "forked one" together in one version number so you can see them both at a glance.
However I do not know whether that's possible.

If so what do you think would be the best way to do this? Some thoughts/ideas of me and a contributor you can find in the issue linked above.

**Comment by FichteFoll** [comment]
This is a long standing discussion. See #264, #265 (probably more).

**Comment by rugk** [comment]
Okay, the only difference I see is that the other issues work with channels. We of course also have different channels, but the version number of *both* should be included in the new whole version number.
E.g. `1.1.2@CE.0.1` instead of just `1.1.2@CE`.

**Comment by jwdonahue** [comment]
@rugk, you can use a build meta tag to encode the other version.  No need for a new kind of field in the SemVer spec.  Unless you have further questions or intend to issue a PR linked to this issue, please close it at your earliest possible convenience.

**Comment by iTrooz** [comment]
If anyone is wondering for a quick solution to this, personally I just appended a part of my username to the versions, e.g. `itr-1.4`
