### ISSUE TITLE
Relation to Semantic Versioning OSGi Whitepaper

### ISSUE THREAD

**Issue by kwin** [semver/semver#280]
There is another whitepaper written by OSGi: http://www.osgi.org/wp-content/uploads/SemanticVersioning1.pdf.
How does your spec relate to that?

**Comment by jwdonahue** [comment]
@kwin, from the executive summary, it's obvious they are not basing theirs on SemVer.  The only relationship is similar names and tertiary similarities in semantics.  Unless you have further questions, please close this issue at your earliest possible convenience.

**Comment by kwin** [comment]
Thanks for the clarification.
