### ISSUE TITLE
Is there any test vectors for testing?

### ISSUE THREAD

**Issue by jinahya** [semver/semver#289]
I'm writing my own library of semver. Is there any formal test vectors for testing?

**Comment by jwdonahue** [comment]
@jinahya 

You can find a list of good and bad version strings we've accumulated over time [here](https://github.com/semver/semver.org/issues/59#issuecomment-390854010). They have been used to test the regex we're trying to get included in the FAQ (see #460).

Unless you have further questions or wish to issue a PR to resolve this thread, please close it at your earliest possible convenience.
