### ISSUE TITLE
How to handle non-api changes?

### ISSUE THREAD

**Issue by Lucretiel** [semver/semver#292]
Let's say I merge a number of pull requests that add a bunch of test coverage, introduce commenting, or update the documentation that ships with the project. How should I handle the version number in these cases? Any or all of these changes could be part of a "release," as they're downloaded with the package. The former case is interesting because it affect people who run the tests, but not the typical client of the library. Are any of these considered "bug fixes," if nothing about the actual usage or API of the project changes? My instinct is to simply revise an existing version (prohibited by [rule 3](http://semver.org/#spec-item-3)). Would this be a patch revision? Build metadata?

**Comment by FichteFoll** [comment]
Imo either minor or patch, depending on how tests are *part of the API*, favoring patch.

**Comment by PowerKiKi** [comment]
I'd go for patch too

**Comment by crazedsanity** [comment]
I increment the patch level in these cases.

**Comment by manbusky** [comment]
Such as performance optimization, I will increase the patch.

**Comment by jwdonahue** [comment]
@Lucretiel, unless you have any further questions on this matter, please close this issue.
