### ISSUE TITLE
There are some format error in a translation version

### ISSUE THREAD

**Issue by haolly** [semver/semver#298]
The item 6, 7 and 8 in http://semver.org/lang/zh-TW/  zh-TW translated version display error, the same as  
zh-CN(http://semver.org/lang/zh-CN/) version

**Comment by Haacked** [comment]
Thanks for the issue. Would you be willing to try and fix it? It's on https://github.com/mojombo/semver.org/. You can even edit the relevant files via the browser.

https://github.com/mojombo/semver.org/blob/gh-pages/lang/zh-CN/index.md
https://github.com/mojombo/semver.org/blob/gh-pages/lang/zh-CN/spec/v2.0.0.md
https://github.com/mojombo/semver.org/blob/gh-pages/lang/zh-TW/index.md
https://github.com/mojombo/semver.org/blob/gh-pages/lang/zh-TW/spec/v2.0.0.md

**Comment by kewang** [comment]
I already fix the issue, wait for accepted. :)

**Comment by haolly** [comment]
@kewang  Good work

**Comment by jwdonahue** [comment]
@haolly, this issue appears to have been resolved with [#139](https://github.com/semver/semver.org/pull/139).  Unless there's a reason to keep it open, can you please close it at your earliest possible convenience?
