### ISSUE TITLE
Problem with plus sign + in semantic version - use web safe underscore _ instead.

### ISSUE THREAD

**Issue by mkboel** [semver/semver#306]
Example: "0.2.0+Metadata" is web unsafe, and is translated to "0.2.0 Metadata" by many web tools.

Many tools use web related url's to refer to versions, but the plus sign + is translated to a space. You should allow a web safe character as delimiter between version and metadata info. Safe characters could be hyphen, underscore, or tilde. 

I suggest sematic versioning use underscore _ as an valid metadata delimiter.

Example "0.2.0_Metadata"

**Comment by FichteFoll** [comment]
The solution is to use `%2B` in web urls, as any url-escaping function does.

**Comment by crazedsanity** [comment]
I agree with @FichteFoll.  It might not seem fair, but going down this road (changing the format to accomodate URL-friendly characters) would pave the way for things like "removing the periods, because those have to be escaped in regular expressions" (which is just a fact of life).

@mkboel, you could create an "extension" of SemVer that swaps `+` for `_`.

**Comment by benmarten** [comment]
We are seeing issues with the plus sign with CocoaPods and with Gradle. It leads to unpredictable builds because they interpret plus sign as anything.
`2.0.0-SNAPSHOT+1493919587` would lead to any snapshot `2.0.0-SNAPSHOT*`
we replaced it with a dot a such: `2.0.0-SNAPSHOT.1493919587`

**Comment by efunkenbusch** [comment]
> 2.0.0-SNAPSHOT+1493919587 would lead to any snapshot 2.0.0-SNAPSHOT*

And that would be correct.  Metadata is not taken into account at all in precedence, and thus two versions that differ only by metadata would be considered identical.

**Comment by jwdonahue** [comment]
@mkboel, unless you have further questions/comments or intend to issue PR, please close this issue at your earliest possible convenience.

**Comment by MairwunNx** [comment]
And what to do with it? How to avoid this when using Gradle? 😵😕

**Comment by mkboel** [comment]
My solution was to stop using the plus sign. And hereby stop using correct
semver. Works like a charm anyway...

tir. d. 14. apr. 2020 19.34 skrev Pavel Erokhin <notifications@github.com>:

**Comment by MairwunNx** [comment]
@mkboel thanks
