### ISSUE TITLE
How to handle version name and version code in Android

### ISSUE THREAD

**Issue by motobhakta** [semver/semver#309]
How to handle version name and version code in Android

**Comment by tdpsk** [comment]
What I typically apply is a versionCode that represents the build number counting up from 1, as this is Google's best practice recommendation. For display purposes in the Play Store and App I apply SemVer to the versionName.

**Comment by jwdonahue** [comment]
@motobhakta, unless you have additional questions, please close this issue at your earliest possible convenience.
