### ISSUE TITLE
Are negative pre-release and build metadata integers allowed?

### ISSUE THREAD

**Issue by johnrs** [semver/semver#324]
I see that negative major, minor, and patch integers are not allowed.  Does this restriction also apply to pre-release and build metadata integers?  For example, in "v1.2.3-beta.-45" or in "v1.2.3--45" would "-45" be a numeric or alphanumeric identifier?

Thanks, John

**Comment by crazedsanity** [comment]
It seems to me that having negative numbers would lead to parsing errors.  And confusion.

Explaining the motivation for your question, or for the implied want to allow them, may help stimulate the conversation.

**Comment by FichteFoll** [comment]
None of these should cause a parsing error (besides the `v` prefix, which is not part of a semver) since hyphens are allowed in both pre-release and metadata identifiers.
What remains unclear is whether numeric characters prefixed with a hyphen should be treated as negative numeric identifiers. The spec itself only mentions that numeric identifiers must not have leading zeros.

**Comment by Haacked** [comment]
> would "-45" be a numeric or alphanumeric identifier?

I'd argue that it would not be a numeric identifier. Alphanumeric refers to `[a-zA-Z0-9]` so the assumption  is numeric is the `[0-9]` portion of the alphanumeric.

Also, when thinking of a numeric identifier, we can look at previous examples (Major, Minor, Patch) to get a sense of the intent. Here's a snippet, emphasis mine:

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are __non-negative integers_, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

I think the intent is pretty clear, but the language is a bit ambiguous and could probably be made more explicit.

**Comment by JacksonBailey** [comment]
Let's get one thing clear, if they are allowed to be present and how they are sorted are two different questions. For both types of identifiers, pre-release and build metadata, yes they are **allowed** (assuming they take from the character set `[0-9-]`).

As for sorting, build metadata does not have a specified way to be sort.

A negative number in pre-release identifiers would be considered text for sorting. See below a portion of item 11 from the spec (emphasis mine).

>identifiers with letters or **hyphens** are compared lexically in ASCII sort order

[Reference](http://semver.org/#spec-item-11)

**Comment by JohnRS** [comment]
Thanks for all the info.  Upon reading the spec again, it does seem that anything with a hyphen is considered an alphanumeric ID, not numeric.  Why is this important?  Sort order.  I'm assuming that numeric ID fields should be sorted in number order as they are in Major/Minor/Patch fields.

I agree that the intent seems clear, but that the language could be more explicit, including both the negative and the sorting aspects for ID's.

Thanks!
