### ISSUE TITLE
Internal version numbers for pre-releases

### ISSUE THREAD

**Issue by magol** [semver/semver#332]
When you install a application in Windows, the application must have a version in the form major.minor.patch, and that match semver. But what do I do with eg. version 1.1.3-rc1

We must have some way of have numerical version numbers for pre-releases.

One (bad) option is not to allow any pre-release for patches and increase the patch version for each pre-release.

| semver | internal version |
| --- | --- |
| 1.8.0-rc1 | 1.8.0 |
| 1.8.0-rc2 | 1.8.1 |
| 1.8.0-rc3 | 1.8.2 |
| 1.8.3 | 1.8.3 |

I don't like it, it is strange. But how should I do?

**Comment by FichteFoll** [comment]
Can't you just use `1.8.0` for all of them? I mean, the main version part is still `1.8.0` and only the pre-release identifier, which Windows doesn't support, changes. Or do these versions have to increment?

**Comment by magol** [comment]
But, if I install 1.8.0-rc2 with version number 1.8.0 and then install 1.8.0-rc3 also with version number 1.8.0, do Windows see any difference between the versions? 

Unless I misunderstood something, MSI will see it as I'm trying to install the same version that I already have with strange results as a consequence. We have in any case not got it to work when we tested.

**Comment by lvv83** [comment]
What about fourth (build) number for internal version? Something like this

semver | internal version
------------ | -------------
1.8.0-rc1 | 1.8.0.1
1.8.0-rc2 | 1.8.0.2
1.8.0-rc3 | 1.8.0.3
1.8.0 | 1.8.0.4

**Comment by magol** [comment]
@lvv83 Great suggestion, but I do think that MSI only care about three numbers :-(

**Comment by lvv83** [comment]
Well, MSI [ProductVersion](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370859(v=vs.85).aspx) is incompatible with semver cause it use `major.minor.build` format. Also it has constraints like maximum value of **255** for `major` and `minor`, **65535** for `build`.

So, we need for some new rule, which translates semver to MSI ProductVersion and vice versa.
We can combine patch and prerelease numbers from semver to the MSI build number. But first we need to replace semver with appropriate internal version. 

semver | internal version | msi version
------------ | ------------- | -------------
1.8.0-rc1 | 1.8.0.1 | 1.8.1
1.8.0-rc2 | 1.8.0.2 | 1.8.2
1.8.0-rc3 | 1.8.0.3 | 1.8.3
1.8.0 | 1.8.0.4 | 1.8.4
1.8.1-rc1 | 1.8.1.1 | 1.8.1001
1.8.1-rc2 | 1.8.1.2 | 1.8.1002

```
internal format is "X.Y.Z.N";
msi_build = Z * 1000 + N 
```

**Comment by magol** [comment]
I like this solution. But it is strange that the numbers go from 4 to 1001.

**Comment by lvv83** [comment]
You can use any rule for msi build number. Yet one without strange gaps.
```
Z >= 0 && Z < 100;
N >= 0 && N < 100;

msi_build = 10000 + Z * 100 + N;
```

semver | internal version | msi version
------------ | ------------- | -------------
1.8.0-rc1 | 1.8.0.1 | 1.8.10001
1.8.0-rc2 | 1.8.0.2 | 1.8.10002
1.8.0-rc3 | 1.8.0.3 | 1.8.10003
1.8.0 | 1.8.0.4 | 1.8.10004
1.8.1-rc1 | 1.8.1.1 | 1.8.10101
1.8.1-rc2 | 1.8.1.2 | 1.8.10102

**Comment by 711216** [comment]
> Cuando instala una aplicación en Windows, la aplicación debe tener una versión con el formato major.minor.patch y que coincida con semver. Pero, ¿qué hago con eg. versión 1.1.3-rc1
> 
> Debemos tener alguna forma de tener números de versión numéricos para las versiones preliminares.
> 
> Una (mala) opción es no permitir ningún prelanzamiento para parches y aumentar la versión del parche para cada prelanzamiento.
> 
> semver	versión interna
> 1.8.0-rc1	1.8.0
> 1.8.0-rc2	1.8.1
> 1.8.0-rc3	1.8.2
> 1.8.3	1.8.3
> No me gusta, es extraño. Pero, ¿cómo debo hacer?

Buscar archivos de mi nube

**Comment by jaques-sam** [comment]
I don't understand your referenced link @grv87, he is not using it for product.
@magol there are 4 numbers available for a version number within EXE & DLLs.
And how do you encode alpha, beta, pre... (are there others?)

**Comment by alexandrtovmach** [comment]
Closing as staled, feel free to re-open or create a new issue :ghost:
