### ISSUE TITLE
Multipale bugs fix increment

### ISSUE THREAD

**Issue by amitosdev** [semver/semver#347]
Let assume my current version is 2.0.0. We found few bugs in different modules. Those bugs are not related to each other but we are planning to fix all of them in the same version. What will be the next version number for this bug fixes? 2.0.1? 2.1.0? or even 2.0.5 (if we have for ex. 5 modules with different bugs in them)?

**Comment by scaytrase** [comment]
The version is not a number of fixed bugs or implemented features. Version is the order (and the compatibility if speaking about semver) identifier for the release

The release numbers are incremented, so while you are not pushing a patch release for each bug the release number should be incremented once. `2.0.1` should be correct here

**Comment by jwdonahue** [comment]
@amitosdev unless you have additional questions, can you please close this issue?
