### ISSUE TITLE
Incrementing semver integers by more than one

### ISSUE THREAD

**Issue by david-kershaw** [semver/semver#356]
Is it acceptable to increment a semver (2) X,Y,Z integer element by more than one? For example is this ok:

    1.9.0->1.10.0->1.20.0

I notice that the 'increment of one' rule was dropped from the doc going from semver1 to semver2.

**Comment by Krinkle** [comment]
It should have been dropped when the doc went from semver1 to semver3.

**Comment by FichteFoll** [comment]
It doesn't state it must be incremented by one, but I don't see any reason not to. You're trying to do something that isn't necessary in semver.

**Comment by sgryphon** [comment]
The stated requirement in Semver 2.0 is to simply to increment, which is different from Semver 1.0 which was to increment by 1.

You can increment by 2, or the Fibonacci series, or whatever, and it will be compliant with SemVer 2.0

**Comment by jwdonahue** [comment]
Requiring increment by 1 can lead to race conditions when you have multiple projects, each adding one or more features. The current wording allows teams to coordinate. Team 1 gets 1, team 2 gets 2, etc. Maybe team 2 beats team 1 to the check-in, so it should just be ok for non-monotonic versions. You just can't allow the same version to ever be applied to more than one package.

**Comment by jwdonahue** [comment]
@david-kershaw yes, perfectly acceptable in accordance with the spec.  If this answers your question, please close this issue at your earliest possible convenience.

**Comment by david-kershaw** [comment]
Thanks for all the answers.
