### ISSUE TITLE
Summary missing for Spanish (ES) version

### ISSUE THREAD

**Issue by josemariasola** [semver/semver#359]
The Spanish version, translated from the English ones, reads a:

Resumen

Dado un número de versión MAJOR.MINOR.PATCH, incrementar la:

versión MAJOR cuando haces cambios incompatibles en la API ,
versión MINOR cuando agregas funcionalidad de una manera compatible hacia atrás, y 
versión PATCH cuando haces correcciones de bugs de una manera compatible hacia atrás.

Etiquetas adicionales para pre-release y metadata del build están disponibles como extensiones al formato MAJOR.MINOR.PATCH.

**Comment by jwdonahue** [comment]
@josemariasola can you edit the title of this issue?  It should read Summary heading missing from Spanish (ES) version.

@mojombo who's the goto person for the translations? Is that GitHub feature?

**Comment by Haacked** [comment]
The translations are in another repository: github.com/semver/semver.org

Even better, consider submitting a PR with a correction. You can [edit it in the browser](https://github.com/semver/semver.org/edit/gh-pages/lang/es/index.md).
