### ISSUE TITLE
Deprecation and how to do it

### ISSUE THREAD

**Issue by dret** [semver/semver#367]
reading that deprecation should be announced via a minor version before being rolled out: would https://tools.ietf.org/html/draft-wilde-sunset-header help as a way to do it? after all, the deprecation notice ideally should be machine-understandable and ideally, this shouldn't have to be re-invented by every single API individually.

**Comment by dret** [comment]
i just added https://github.com/dret/I-D/commit/d5b738d49e59b124dcee84cee8f3e435efecb293 (deprecation) as one scenario to the draft. i am planning on publishing a new version soon.

**Comment by jwdonahue** [comment]
It seems likely that for service interfaces over HTTP, [https://tools.ietf.org/html/draft-wilde-sunset-header](https://tools.ietf.org/html/draft-wilde-sunset-header) would be a wise choice, in conjunction with the specified SemVer behavior.  

The Sunset HTTP Header is beyond the scope of the SemVer specification.  Please close this issue at your earliest convenience.

**Comment by dret** [comment]
not a problem. thanks for looking into it.
