### ISSUE TITLE
https://semver.org/ is insecure

### ISSUE THREAD

**Issue by majgis** [semver/semver#369]
https://letsencrypt.org/

**Comment by FichteFoll** [comment]
https://github.com/mojombo/semver.org/issues/86

**Comment by jwdonahue** [comment]
@majgis, this issue seem to have been fixed, see semver/semver.org#86.  Please close this issue at your earliest possible convenience.  Thank you.

**Comment by jwdonahue** [comment]
@majgis , please close this issue.
