### ISSUE TITLE
Missing question mark

### ISSUE THREAD

**Issue by johananl** [semver/semver#373]
Hi,

I've noticed a missing question mark in [this](http://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release) FAQ question.

The rest of the questions in the FAQ section do have question marks at the end, so I assume this one should do, too.

Thanks!

**Comment by Haacked** [comment]
Good catch! Want to submit a PR?

**Comment by johananl** [comment]
Sure, there you go :-)
https://github.com/mojombo/semver/pull/374
