### ISSUE TITLE
NumberFormatException when pharsing versions like 2.8.1414098270477  & 0.0.111111111111

### ISSUE THREAD

**Issue by itay-keller** [semver/semver#383]
Hi,

Where semver is trying to pharse versions like   it gets a NumberFormatException:

2.8.1414098270477 

> Exception in thread "Thread-17" java.lang.NumberFormatException: For input string: "1414096209398"
>         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
>         at java.lang.Integer.parseInt(Integer.java:583)
>         at java.lang.Integer.parseInt(Integer.java:615)
>         at com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:289)
>         at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
>         at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
>         at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)

**Comment by msitte** [comment]
your number is too long for an int. you'd have to use long instead: java.lang.Long.parseLong

**Comment by itay-keller** [comment]
These are not my version numbers, but versions I stumbled upon when using semver.
Maybe semver can change parseVersionCore to use long instead of int.

**Comment by FichteFoll** [comment]
You are referring to a specific implementation of semver, while this repo is about the specification. Semver does not impose a maximum number for its parts (e.g int or long), however there is an issue discussing this. I'm on mobile rn, but it shouldn't be hard to find.

**Comment by jwdonahue** [comment]
@itay-keller, the most likely repo's that house the code you referenced can be found here:

https://github.com/search?utf8=%E2%9C%93&q=zafarkhaja&type=

Please close this issue.
