### ISSUE TITLE
Marketing and Third-Party compatible semantic versions

### ISSUE THREAD

**Issue by ScreamingDev** [semver/semver#385]
Here is a breaking change for SemVer which might come with Semver 3:

Currently versions are like "Major.Minor.Patch" for a package.
This is quite confusing when there is a third party involved (like an API or Marketing):

- API connector grows to version 3.5.6 while API is still 1.0.0.
- API grows from 1.0.0 to 2.0.0 while API-connector package has to grow from 7.4.2 to 8.0.0 - hard to connect in mind.
- Marketing wants to distribute current solutions as v1 (like Magento) and don't care about internal breaking changes.

So another form of semver is needed like: `{arbitrary-version}.{major}.{minor}.{patch}`.
Or a more generic approach just saying: "The last three numbers need to follow semver, everything in front can be as anyone wants it to be."

This solves the common issue and brings more freedom among devs, sales and third-party:

- Marketing allows breaking changes and still want's to give developers the freedom to mark them somehow.
- API grows from 1.2.3 to 2.0.0 so can the api-connector do from 1.22.33.44 to 2.0.0.0 , which is easy to follow for non-technical people.
- Sales can at anytime invest in redoing some app (v3.2.1.0) from scratch which leads to the brand new refurbished (v4.0.0.0).

**Comment by FichteFoll** [comment]
Sounds like you should encode the target api version in the metadata segment of the connector's semver.

**Comment by silkentrance** [comment]
semver is not about marketing. you need to straighten up your processes.

And there is no reason why ``api connector`` shouldn't be using a different version than its api dependency.

As for Marketing wanting to release a v1 version, just tell them no. They can communicate such a version to the public, but internally it will be totally different.
Which, of course, has been the best practice since the time that Marketing tried to evolve from being just a utility to wanting to control overall development. 

As for ``{arbitrary-version}.{major}.{minor}.{patch}``, I personally refer to these as star dates, as in Star Trek. Absolutely artificial and overly redundant.

**Comment by jwdonahue** [comment]
Marketing and package naming/decorating conventions do not fall within the purview of SemVer, though I do think it should at least link to some common best practices. The packages names do in fact carry semantic content that can be relevant to consumers trying to make informed choices.

**Comment by jwdonahue** [comment]
Related #265, #352.

**Comment by jwdonahue** [comment]
@ScreamingDev, unless you intend to submit a pull-request or have further questions, can you please close this issue at your earliest possible convenience?  Thank you.

**Comment by silkentrance** [comment]
@ScreamingDev you might also want to consider tags on your semver, e.g.

```
api-connector@44.5.2-APIv1.0
```

if that suits you, otherwise, encode the API version in the api-connector's package name, e.g.

```
api-connector-APIv1@44.5.2-BETA.0
```

**Comment by markusschaber** [comment]
As Marketing tends to rework the versioning in very irrational ways[1], it's hopeless to combine it with semantics of any kind.

You could allow some Syntax to inject Marketing labels which are just ignored for SemVer. One idea could be "Label (SemVer)" - just include the Semantic Version into brackets, and ignore everything outside the brackets.

Using a Fullstop character to split semantic and non-semantic part might be very hard for (human and machine) parsers to get right, and also cause confusion with existing legacy 4-digit numbering schemes.

[1] a popular example is Windows: 1.0 - 2.x - 3.0 - 3.00a - 3.0 with Multimedia Extensions - 3.1 - 3.11 - 95 - 95a - 95b - 95b OSR 2.1- 95c - 98 - 98SE - ME - 2000 - XP - XP - Vista - 7 - 8 - 8.1 - 10

**Comment by ScreamingDev** [comment]
Thanks @markusschaber and @silkentrance for your words and hints.
This remains an issue for me but for our API this has come to an easy solution:

- The API is version 1.x.y
- The SDK is "api-sdk v1-44.5.2" or "api-sdk v1.1-44.5.2"

As long as the API follows semver and assures backward compatibility and no breaking changes in Version 1 we can safely use the "foreign version" as a prefix or within the package name. This is hopefully understandable by non-developers and developers.

All other things like "Hey, my Plugin is compatible with a douche app that has arbitrary versioning" remain a feature request to semver.

**Comment by jwdonahue** [comment]
@ScreamingDev, see [VersionMeta](https://versionmeta.org/) and [VersionSchema](https://versionschema.org/). Both a work in progress, but I could really use some feedback from potential adopters.

Unless you intend to offer a pull-request or have any other related questions, can you please close this thread at your earliest possible convenience?

**Comment by jwdonahue** [comment]
@silkentrance ,

 Yup, I need to fix that. For now, I edited the link.  Thanks.

**Comment by jwdonahue** [comment]
@ScreamingDev, why is this issue still open?

**Comment by jwdonahue** [comment]
@ScreamingDev, unless you have further questions or intend to issue a PR, please close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@ScreamingDev , please close this issue.

**Comment by jwdonahue** [comment]
@ananqaur, @dherman, @indirect, @isaacs, @segiddins, @steveklabnik, @Seldaek ,

Any of you see any reason to keep this thread open?  If not, please tag it as you see it fit and close it at your earliest possible convenience.

**Comment by joeboon** [comment]
The OP examples are wrong. Based on their proposal, it would go from
- api-connector: 1.22.33.44 to 2.23.0.0 because {major} would increase (not 2.0.0.0)
- some app: 3.2.1.0 to 4.3.0.0 (not 4.0.0.0)
