### ISSUE TITLE
Can't find SemVer 2.0.0 incompatibility documentation

### ISSUE THREAD

**Issue by breyed** [semver/semver#387]
Since the new version of SemVer is 2.0.0, the implication is that it is in some way incompatible with SemVer 1.0.0 (otherwise the new version would have been SemVer 1.1.0). This tells me that I should expect to have to unlearn something I knew about 1.0.0, in additional to learning about 2.0.0's new functionality.

I couldn't find any clue about the changes from the [home page](http://semver.org/). Are there release notes that document the breaking changes and new functionality? If so, it would be a good idea to link to them from the home page.

**Comment by magol** [comment]
I agree. Please add a [changelog.md](http://keepachangelog.com) and link to it from the home page

**Comment by BM5k** [comment]
https://github.com/mojombo/semver/compare/v1.0.0...v2.0.0#diff-55782f4857216898d46c6eca25fc5f32

**Comment by silkentrance** [comment]
Please close and get rid of these closable open issues ASAP.

**Comment by Haacked** [comment]
I think @BM5k answered the question.
