### ISSUE TITLE
#388

### ISSUE THREAD

**Issue by vliparsov** [semver/semver#389]
ehm

**Comment by jwdonahue** [comment]
@vliparsov, please add a title and a body to this issue or remove it at your earliest possible convenience.

**Comment by vliparsov** [comment]
.

**Comment by jwdonahue** [comment]
@Haacked, this is noise and vliparsov seems to think this is a game.  Several more examples of there noise can found at https://github.com/semver/semver/commit/e41de1726465b60588aa0d25cb7fb8ed51c8b84b#commitcomment-26404536

**Comment by Haacked** [comment]
@jwdonahue Thanks! I've blocked the user from the org.
