### ISSUE TITLE
Weird alphanumeric-identifier grammar allowing "1.2.3----+----3.2.1" as a correct version number 

### ISSUE THREAD

**Issue by nowox** [semver/semver#405]
I feel bizarre to allow `-` after the `dash`. The given grammar perfectly allows version such as

```
1.2.3----+----3.2.1
```

Is it really wanted?

**Comment by akalongman** [comment]
If developer is stupid, you can not fix that via specifications or rules :)

**Comment by nowox** [comment]
You can at least refuse the `-` which is confusing...

**Comment by jwdonahue** [comment]
Hyphens are legal characters in prerelease and meta identifiers.  There might actually be some automation out there that would generate such a perfectly valid version string, say, when the user failed to initialize some database/configuration fields.

**Comment by jwdonahue** [comment]
I believe this should be closed as won't fix. The tag identifiers are not empty and contain legal characters.

**Comment by Haacked** [comment]
Not really wanted, but not really unwanted. Feels like it'd needlessly complicate the spec to clean this scenario up. Closing as "won't fix"
