### ISSUE TITLE
Announcing the new digs!

### ISSUE THREAD

**Issue by Haacked** [semver/semver#408]
Hi All,

If you hit the URL for the semver repository, you may have noticed that you've been redirected to a new URL. This is because the semver spec and site now live within the "semver" GitHub org.

This is the result of @zeke contributing the semver org to this effort and @mojombo, the creator of semver, transfering the repositories to this org.

Please join me in expressing gratitude to these two folks! I think an org is the right place for Semver related work.

**Comment by Haacked** [comment]
I also have access to the DNS. I hope to get https enabled, at which point I'll probably blog and tweet about the changes for more exposure.

**Comment by mojombo** [comment]
Thanks for making this happen, @Haacked. Excited to see the improvements!

**Comment by alphapapa** [comment]
FYI, http://semver.org is currently failing DNS lookup, but I guess you already know that--just making sure.  :)

**Comment by polyzen** [comment]
> I hope to get https enabled

https://github.com/isaacs/github/issues/156

**Comment by zeke** [comment]
🎉 Thanks for making this happen, @Haacked.

**Comment by zeke** [comment]
I went ahead and updated the org's website URL from my [semver.io](https://semver.io/) project to `http://semver.org`

**Comment by war59312** [comment]
How to serve a custom HTTPS domain on GitHub Pages with CloudFlare: *FREE*, secure and performant by default: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b
