### ISSUE TITLE
semver/semver needs a wiki.

### ISSUE THREAD

**Issue by jwdonahue** [semver/semver#412]
Well I already started the wiki page (semi-retired/bored!).  I was actually shocked that I had permission to create one, but it's a good sign.  I would appreciate it if whoever is currently "in charge" around here would please contact me ([joseph@odonahue.com](mailto:joseph@odonahue.com)), I'd like to get the wiki page fleshed out with more than just TODO's before EOY.  Either take a stab at the TODO's on the wiki page, or contact me with the essential details and I'll crank out some drafts.

Any and all feedback on this issue is welcome and encouraged, I promise to address them in a timely fashion, but I would also like to encourage others to just dive into the wiki if you have the time.  If all you do is add reference links to related pages, it will help a lot. I can back-fill the prose after reviewing the linked content.

**Comment by jwdonahue** [comment]
One good use of the Wiki's here at GitHub would be to introduce Engineering Notes. Basically white papers on particular subjects that might provide background for starting new efforts on the site or to flesh out best practices around using SemVer in the real world.

**Comment by jwdonahue** [comment]
Well it appears my wiki attempt has been removed.  Closing this issue for now.

**Comment by jwdonahue** [comment]
In light of the new management team, I am reopening this for consideration.  We were just starting to evolve a wiki to cover useful bits of info that doesn't belong in issues, when it got pulled.  Over the past couple of years, I have found myself answering very similar questions with similar answers.  A wiki would allow us to provide detailed and nuanced write-ups on common topics, that can't be covered adequately, or as easily, in the FAQ.  We could then reference those wiki pages in responses to issues raised here, and improve the quality and uniformity of support provided.  A non-normative media would allow for the kind of subjective exposition that enhances understanding of cold-logical specs.

**Comment by steveklabnik** [comment]
I personally find wikis to to a dumping ground of unmaintianed misinformation. But if the rest of the team wants one, sure.

**Comment by jwdonahue** [comment]
That can definitely happen if we don't keep an eye on it.  Another option would be to add a "white-papers" section to the official web site and post a formal process for getting them approved.  I'd be willing to contribute.

**Comment by segiddins** [comment]
I agree with steve -- I prefer content be tracked in a git repo, and go through PRs. I personally avoid maintaining wikis whenever possible.

**Comment by jwdonahue** [comment]
As per my own rules regarding the likelihood of getting any traction, I am closing this issue.
