### ISSUE TITLE
Unable to find version '1.0.0' of package 'SemanticVersioningToolset'.

### ISSUE THREAD

**Issue by Richy333** [semver/semver#417]
I'm trying to build a .NET project made by other developer.
I get the following error:

Unable to find version '1.0.0' of package 'SemanticVersioningToolset'.

I can't find this package in the file system.
I searched online, but I could not find information about it.

Does anyone know this package?

**Comment by jeme** [comment]
This does not belong here...

You need raise this with those "other developers" as they are the only ones who will have the answer...

**Comment by jwdonahue** [comment]
@Richy333, unless you have further questions, please close this issue at your earliest possible convenience.
