### ISSUE TITLE
SemVer does not use SemVer for releases

### ISSUE THREAD

**Issue by variadico** [semver/semver#424]
From [semver.md](https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version), 
> "v1.2.3" is not a semantic version

yet all of semver's releases prepend a `v`.

https://github.com/semver/semver/releases

[semver.org](https://semver.org/) correctly trims the prefix.

**Comment by FichteFoll** [comment]
This is explained in https://github.com/semver/semver/issues/235. TL;DR: a "git tag" is not a semantic version.

**Comment by jwdonahue** [comment]
CoolLib.1.0.0.pkg  is not a semver string either, but it contains a semver substring.  The spec doesn't address decoration/naming conventions.  [Initially, the spec](https://semver.org/spec/v1.0.0-beta.html) did include a leading v and that was dropped fairly early on.

**Comment by jwdonahue** [comment]
@variadico, SemVer addresses the syntax and semantics of a specific kind of version string. It says nothing about anything else on the page. If you go to https://semver.org/ you will not find any v's in front of any of the specifications version strings, nor are they used in any of the examples.

Unless you have further questions, please close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
@variadico , please close this issue.
