### ISSUE TITLE
Invalid example in 2.0.0 clause 9

### ISSUE THREAD

**Issue by hleeanexinet** [semver/semver#426]
The clause 9 says: "Numeric identifiers MUST NOT include leading zeroes."

Then, in the example "1.0.0-0.3.7" in the same clause, what's the 0 right after the hyphen?

**Comment by hleeanexinet** [comment]
OK, it's not a leading zero. Leading zero has to be followed by a non-zero digit.

https://en.wikipedia.org/wiki/Leading_zero

**Comment by RichardDavies** [comment]
I had the exact same thought as I read the spec! After studying it, it became clear to me what the author meant, but the term "leading zero" is somewhat ambiguous as the technical definition differs slightly from the natural "semantic definition" conveyed by the words (i.e. a leading zero is any zero that appears as the first character before other characters). 

It's obvious that [we're not the only ones to make this incorrect assumption](https://github.com/semver/semver/issues/348) so maybe the spec should clearly define that term or link to the definition of "leading zero" whenever that term is used.
