### ISSUE TITLE
Is there a formally defined name for x.0.0 and x.y.0 versions?

### ISSUE THREAD

**Issue by jleeothon** [semver/semver#427]
If I understand correctly, given version "X.Y.Z", "major" and "minor" and "patch" do formally refer to the X, Y, and Z respectively.

If so, is there a name for the "X.0.0" and the "X.Y.0" versions? E.g. 1.2.0 is the "minor release immediately before" 1.2.3?

**Comment by FichteFoll** [comment]
I would think of it as branches. All versions with major version 1 are on the "major 1" branch, which in return can be split into, e.g., "1.2" and "1.0" branches.

Not sure if there is any remotely adopted standard about these.

**Comment by jwdonahue** [comment]
> If so, is there a name for the "X.0.0" and the "X.Y.0" versions? E.g. 1.2.0 is the "minor release immediately before" 1.2.3?

Yes. We basically have major, minor and patch releases. 1.2.3 is a patch release following 1.2.1, which follows 1.2.0, which was a feature release.  2.0.0 would be referred to as a major or breaking change release. Note that gaps in the available version numbers should normally indicate the withdrawal of a version from the feeds/file-shares, not its absence from version history.  Nothing in the spec says you can't skip some number of versions on the publication side, but it's not really normal.

**Comment by jwdonahue** [comment]
@jleeothon, unless you have further questions, please close this issue at your earliest possible convenience.
