### ISSUE TITLE
Questions about Minor Changes

### ISSUE THREAD

**Issue by jon-whit** [semver/semver#429]
According to the SemVer specification, the MINOR version MUST be incremented if new backwards compatible changes are made to the public API.

What if new functionality is added to an internal API that doesn't change the public API? Are there any recommendations on bumping version numbers if the internal API changes but does so in a way that is compatible with the existing public API? Should the version be bumped at all in this case?

**Comment by foxbit19** [comment]
Hi @jon-whit, I think there must be an increase of the MINOR version even if the new functionality is added to an internal API. The version increments represent a change that distinguish previous version from current version of your code.
I always think about incremental code obfuscation in this case: consequentials releases (with different version numbers) that are semantically equivalent but hardening the reverse engineering job.

**Comment by FichteFoll** [comment]
The internal API is completely separate from the public API and does not matter in the semver scope. Changing *anything* in the internal API is entirely transparent to the public API, so this is a patch level change,

**Comment by jwdonahue** [comment]
> According to the SemVer specification, the MINOR version MUST be incremented if new backwards compatible changes are made to the public API.

Actually it doesn't say that at all.  You are referring to https://semver.org/#spec-item-7, which references the public API. It does say that it MAY be incremented "if substantial new functionality or improvements are introduced within the private code".

@jon-whit, unless you have further questions, please close this issue at your earliest possible convenience.

**Comment by jon-whit** [comment]
@jwdonahue thanks!
