### ISSUE TITLE
Home page and link to spec v2.0.0 are different

### ISSUE THREAD

**Issue by Relequestual** [semver/semver#454]
The content of https://semver.org/ (which is titled 2.0.0), and the link for 2.0.0 (which is https://semver.org/spec/v2.0.0.html) are different.

The home page has a tiny language bug fix which doesn't effect "functionality", but shouldn't that change, even of a single word, have resulted in a patch version bump?
OR is the assumption that fixing typos / correcting bad words doesn't warrant a patch release?

If I'm referencing 2.0.0 somewhere, I want to use the 2.0.0 link, in case a newer version is released and lands on the home page, right?

**Comment by jwdonahue** [comment]
I think the home page should simply redirect to the v2.0.0.html file.  That would eliminate any chances of them ever getting out of sync again.  As for the advertised spec version, I think that probably refers to the content of the [Semantic Versioning Specification section](https://semver.org/#semantic-versioning-specification-semver).  But I do agree with you. I think we should have seen some version bumps along the way.

**Comment by beruic** [comment]
I am glad I am not the only one that saw this dreaded discrepancy

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/semver/semver/issues/407 which is older. Thanks!

**Comment by Relequestual** [comment]
@steveklabnik But that issue includes the markdown file in the repo too, which has been noted is "development", which is fine.
