### ISSUE TITLE
fix bug - new feature same time

### ISSUE THREAD

**Issue by elmer120** [semver/semver#455]
Hi to all!

I have a question. 
In the previous state of 1.0.0, if for example the software is at 0.1.1-alpha. 
If I do this I'll correct a bug but at the same time add a new feature. 

Is it correct to go from 0.1.1-alpha to 0.2.0-alpha?

thanks

**Comment by grv87** [comment]
@elmer120, in before-1.0.0 state I personally follow all the rules as in post-1.0.0 except Rule 8 about breaking changes.
If you fix a bug and add a feature then Rule 7 replaces Rule 6, and you should increase minor and reset patch to 0.
So, you are correct. You should go with `0.2.0`.
About `alpha` pre-release label: if you follow current version of SemVer strictly, then it is not required. All versions before `1.0.0` are pre-releases, no need to signify that.
But if you think that [`magic zero` rule could be mistake](https://github.com/semver/semver/issues/221) then `alpha` pre-release label is required.

**Comment by jwdonahue** [comment]
@elmer120, is there anything else you need help with?
