### ISSUE TITLE
No hungarian version!

### ISSUE THREAD

**Issue by esztermarton** [semver/semver#469]

**Comment by jwdonahue** [comment]
@esztermarton 

Are you volunteering to help with that?

**Comment by esztermarton** [comment]
Absolutely. Pull request to follow soon. :)

**Comment by koviroli** [comment]
@esztermarton I thought the same today. I would be happy if could help. Have you got repository where hungarian translation is already in progress?

**Comment by jwdonahue** [comment]
Hopefully, @Haacked will chime in here soon and point you in right direction.

**Comment by Haacked** [comment]
Jo Napot Kivanok!

A Hungarian translation would be welcome. All translations are done in https://github.com/semver/server.org

**Comment by esztermarton** [comment]
@koviroli Apologies for the delay - i was in portugal running a marathon and didn't get much time to push this up even... 

One of the unexpectedly hardest things I've done in a while, I can't believe how difficult it is to translate technical stuff. I've already got loads of untranslated words there with question marks next to them - didn't have internet yesterday to google - but if you guys don't even need googling please do edit!

I will be working on it on and off this week - please make sure you always push up your work v frequently so none of us duplicate effort. :) & thanks very much for the help!

https://github.com/esztermarton/semver.org/tree/hungarian

**Comment by esztermarton** [comment]
Sure, here is fine by me, up to you! keen to hear your thoughts

**Comment by koviroli** [comment]
I've seen u started translating from the top, so I started to translating from the bottom. This way there won't be conflict for the first some commits. Forked from ur repo, already sent a pull request to u.

**Comment by esztermarton** [comment]
question: should we keep paragraphs as a single line (as in the english version), or by arbitrarily pressing enter after a certain number of characters so that it roughly keeps the width as in the english version? happy either but would like to be consistent throughout.

**Comment by jwdonahue** [comment]
That's a question for @Haacked.

**Comment by koviroli** [comment]
This issue can be closed. :) 

[PullRequest#203](https://github.com/semver/semver.org/pull/203)
