### ISSUE TITLE
Replacing "when" by "when and only when"?

### ISSUE THREAD

**Issue by patricekrakow** [semver/semver#475]
Let's take the 1st statement as an example:

> [...] increment the MAJOR version *when* you make incompatible API changes [...]

It means that you **can** increment the MAJOR version *even when/if* you do **NOT** make incompatible changes! So, as a consumer of the public API of the package, if I see an increment of the MAJOR version, I do **NOT** know if I have to change my application or not? This is why I would prefer to see:

> [...] increment the MAJOR version ***when and only when*** you make incompatible API changes [...]

What do you think? Does that make sense? Or is it **on purpose** that MAJOR version can be incremented *without* incompatible API changes?

**Comment by sheldonh** [comment]
Ask yourself why you would want to prevent me from arbitrarily bumping the MAJOR version number for reasons you haven't considered.

**Comment by jwdonahue** [comment]
@patricekrakow, unless you intend to issue a PR or you have further questions, please close this issue at your earliest possible convenience.

**Comment by patricekrakow** [comment]
I think we all agree that the notions of _incompatible/breaking changes_ and _backwards compatible changes_ are relative. So even if the producer/provider thinks that the changes will be backwards compatibles for all her/his consumers, still some consumers applications can be broken. I really like the story in <https://increment.com/apis/web-api-versioning/#defining-backward-compatibility> and I am not questioning that.

What I am saying is that the semantics of a semantic version should be strictly limited to the belief of the producer/provider about the incompatible/breaking or backwards compatible nature of the changes she/he is proposing to her/his consumers, and not about any other considerations such as:

* This change took me a long time to implement, it deserves an increment of the MAJOR;
* It has been a while I am on the same major, the next change, whatever it is, I will increment the MAJOR;
* We want to show off the great work we have done by incrementing the MAJOR;
* ...

@sheldonh you wrote: _Ask yourself why you would want to prevent me from arbitrarily bumping the MAJOR version number for reasons you haven't considered._ And my answer is that I would like to prevent you from abusing the semantics of semantic versioning. I hope it makes sense...

@jwdonahue I should now indeed create a PR. With or without "RFC" tag, that's the question...

**Comment by ljharb** [comment]
@patricekrakow it is in no way abuse to bump the major even if there's no breaking changes.

**Comment by rgwilton** [comment]
Hi,

This discussion is interesting, and this topic (https://github.com/netmod-wg/yang-ver-dt/issues/78) has come up during the discussion of an IETF YANG versioning solution is based around Semver 2.0.0.  https://www.ietf.org/archive/id/draft-ietf-netmod-yang-module-versioning-02.txt

Interestingly, my reading of the Semver spec seemed to match @patricekrakow's interpretation, but another IETF colleague has taken an interpretation closer to @jwdonahue.  Specifically they would like the flexibility to bump the major version number when they release new major product versions, to give more flexibility to add backwards compatible enhancements to products that have been released and the software is being maintained.

But the key point is that different people are interpreting the Semver 2.0.0 spec in different ways, and that probably isn't helpful.

Hence, if the interpretation of Semver 2.0.0 is that flexibility is allowed, then it would arguably be helpful to clarify that in the Semver specification to remove the ambiguity.

Conversely, if it is not allowed, then it would also be helpful if the specification was strengthened to make that explicit.

Regards, Rob

**Comment by patricekrakow** [comment]
See #619 for my final words.
