### ISSUE TITLE
minor or patch change for a configuration change?

### ISSUE THREAD

**Issue by jruts** [semver/semver#476]
If we change a piece of configuration in the code, would we then increase the _patch_ version or the _minor_ version?

Do note that this is in a Terraform project so the change is technically a code change (since Terraform is infrastructure as code).

I ask this question because it specifically says that the path version is for bux fixes and this causes confusion. 

Kind regards.

**Comment by jwdonahue** [comment]
@jruts, unless you have further questions or comments, please close this issue at your earliest possible convenience.

**Comment by jruts** [comment]
Thanks for the reply!
