### ISSUE TITLE
Membership request for Composer

### ISSUE THREAD

**Issue by Seldaek** [semver/semver#495]
As PHP's dependency manager, Composer also encourages users to follow semver (our implementation is at https://github.com/composer/semver) as closely as possible. We definitely have some minor variations already due to historical reasons and things introduced in semver 2.0 IIRC.. 

But in any case we value interop between ecosystems (although it's mainly programmer "mind" interop we are talking about here I believe). We for example added the `^` operator to be compatible with npm as a ton of our users also use npm to some extent. 

I would be happy to join the team and be on watch here, if only to sanity-check RFCs in terms of BC for our ecosystem.

**Comment by steveklabnik** [comment]
I think having Composer along would be great, personally! @semver/maintainers , if you could check a box if you agree, or post a comment to this thread if you disagree and/or have questions to make sure @Seldaek is on the same page as the rest of us, that'd be great.

@Seldaek you've read https://github.com/semver/semver/blob/master/CONTRIBUTING.md#participation-commitment, right? I'll check my box after you've confirmed so :)

- [ ] @anangaur 
- [ ] @dherman 
- [ ] @indirect 
- [ ] @isaacs 
- [ ] @segiddins 
- [ ] @steveklabnik

**Comment by Seldaek** [comment]
Yup, read it and it all sounds reasonable to me.

>

**Comment by steveklabnik** [comment]
Great, we have consensus! @Seldaek I've sent you an invite to the team. Welcome! ❤️

**Comment by stof** [comment]
shouldn't https://github.com/semver/semver/blob/master/CONTRIBUTING.md#the-semver-team be updated ?

**Comment by anangaur** [comment]
Can we just merge this PR: https://github.com/semver/semver/pull/500 and @Seldaek can raise another one to add self?
