### ISSUE TITLE
membership request for Go

### ISSUE THREAD

**Issue by rsc** [semver/semver#498]
Go uses semver to describe versions of Go modules.
We care about being consistent with the rest of the
languages where there is meaningful overlap.

I agree to the [participation commitment](https://github.com/semver/semver/blob/master/CONTRIBUTING.md#participation-commitment).

Thanks.

**Comment by steveklabnik** [comment]
Having Go on board sounds fantastic to me!

@semver/maintainers , if you could check a box if you agree, or post a comment to this thread if you disagree and/or have questions to make sure @rsc is on the same page as the rest of us, that'd be great.

- [ ] @anangaur 
- [ ] @dherman 
- [ ] @indirect 
- [ ] @isaacs 
- [ ] @segiddins 
- [x] @steveklabnik

**Comment by isaacs** [comment]
@rsc Is there a standalone SemVer implementation to point to?  I'm not too familiar with Go, sorry.  But we should really get a list of these things along with the package managers they power.

**Comment by rsc** [comment]
@isaacs The implementation used by the `go` command (the "package manager") is at https://golang.org/src/cmd/go/internal/semver/semver.go. It's not a published API for others to use.

**Comment by JohnTitor** [comment]
Hey @rsc, sorry for the long delay, but it seems there's no objection and I'd like to call it the consensus. Let me know if you are still interested in helping the semver work! We'll then add you to the team as per https://github.com/semver/semver/blob/master/CONTRIBUTING.md#the-semver-team.

**Comment by JohnTitor** [comment]
I will close this as there's been no response for over 2 months. Feel free to reclaim if you're still interested in the semver spec maintenance!
