### ISSUE TITLE
Are you allowed to publish an older minor version after a major version?

### ISSUE THREAD

**Issue by rgwilton** [semver/semver#504]
Say the following versions have been chronologically released: 1.0.0 -> 1.1.0 -> 2.0.0.

Does the scheme allow software to subsequently release a version 1.2.0 after 2.0.0 has been released?  1.2.0 would obviously be based on 1.1.0 with backwards compatible changes.

My working assumption is that because the scheme does not disallow this, then this is in fact allowed.

**Comment by lirantal** [comment]
Makes sense to allow it. One important requirement for this is back-porting of security fixes to previous versions.

**Comment by ljharb** [comment]
It’s absolutely critical, yes. For backporting of anything, including features.

**Comment by segiddins** [comment]
SemVer doesn't say anything about _when_ you publish which versions, only about how those versions relate to each other. You're free to publish a "lower" version at any time, so long as it's the appropriate version for the changes it contains _relative to the newest version less than that version_.

**Comment by Haacked** [comment]
I agree with @segiddins.

> You're free to publish a "lower" version at any time, so long as it's the appropriate version for the changes it contains relative to the newest version less than that version.

The one thing to be careful about is to make sure the package registry doesn't mark this as the latest version. I assume most hosts will do the right thing and mark the highest version number as the latest, but I've written software before and I know how it can sometimes not do what it should. 😛

**Comment by ljharb** [comment]
To protect myself against that with npm, I made and use https://npmjs.com/safe-publish-latest :-)

**Comment by jwdonahue** [comment]
See [my reply](https://github.com/semver/semver/issues/484#issuecomment-465000656) to #484.

**Comment by isaacs** [comment]
Yes, SemVer is 100% time agnostic.

In npm, you can publish an older version and avoid marking it as `latest` by using the `--tag` command line option.  I usually do `npm publish --tag=legacy` for updates to previous versions, and `npm publish --tag=next` for release candidates that are not yet ready for being the default distribution.
