### ISSUE TITLE
Rename semver.md to README.md for preview

### ISSUE THREAD

**Issue by munierujp** [semver/semver#509]
GitHub shows `README.md` on repositroy page.
So, I think that `semver.md` should be renamed to `README.md`.

**Comment by grv87** [comment]
Why not just make PR?

**Comment by Playermet** [comment]
https://github.com/semver/semver/pull/527

**Comment by alexandrtovmach** [comment]
Unfortunately @Playermet closed their PR after long delay

**Comment by alexandrtovmach** [comment]
Renaming semver.md to README.md is not good idea :thinking: _README_ should contain **info about** the project, but _semver.md_ **this is** a project. I've added README with links to both markdown file and website

**Comment by munierujp** [comment]
@alexandrtovmach I think so too. Thanks😄
