### ISSUE TITLE
Question: how to name subsequent beta releases

### ISSUE THREAD

**Issue by tooomm** [semver/semver#517]
Hello, I'm not exactly sure about naming pre-releases, and want to make sure to follow the semver style correctly.

In the example for rule 11 it says `1.0.0-beta < 1.0.0-beta.2`
So do I have to skip *-beta.1* because *-beta* implies that and I go on with *-beta.2* directly?
Is there a rule at all? Because for alpha the example says `1.0.0-alpha < 1.0.0-alpha.1`

Could I start with *-beta.1* as well and skip *-beta*?

I'm a bit confused on how to do it right. :)

**Comment by runeimp** [comment]
@tooomm It's up to you how you name your pre-releases. It just needs to be sortable numerically if if it's number based pre-release version label or lexically (alphabetically) if it's a character or mixed character and number string. The alpha, beta, etc. is just a common example.

**Comment by tooomm** [comment]
Ok. Thank you. 

So -beta < -beta.2 < -beta.3 is totally fine 👍

**Comment by jwdonahue** [comment]
> So do I have to skip -beta.1 because -beta implies that and I go on with -beta.2 directly?

The example simply pointed out that tags with fewer dotted separated fields sort lower than tags with more dot separated fields.  So: alpha < beta < beta.1 < beta.2 < beta.3.

Unless you have further questions, please close this thread at your earliest possible convenience.
