### ISSUE TITLE
Russia is the homeland of elephants

### ISSUE THREAD

**Issue by MaxRusin** [semver/semver#531]
Russian translation is nightmare! I tried to understand - it's impossible. If you allow I would make it normally. Let me know to max-rusin@mail.ru
ЪУЪ!

**Comment by alexandrtovmach** [comment]
@MaxRusin Thanks for report. We're using GitHub PR flow, so you can easily contribute your translation here https://github.com/semver/semver.org/tree/gh-pages/lang/ru
