### ISSUE TITLE
[PROPOSAL] : breaking change bit in the version number

### ISSUE THREAD

**Issue by anikethsaha** [semver/semver#543]
Outline
---
as of v2 (not sure about v3 ), sematic versioning supports three types of versioning

- major <vX.0.0>
- minor <v0.X.0>
- patch <v0.0.X>

I am proposing to have the 4th bit in the version number as breaking change bit.

## Proposing Breaking change bit or flag (v0.0.0.X)

Here the 4th number will be either `0` or `1`. which will specify whether the release contains any breaking change or not.

**Examples**

- v4.0.0.1 - a major release contains breaking changes
- v3.5.0.0 - a minor release contains no breaking changes
- v3.2.2.1 - a patch release contains breaking changes

## Why

A release whether it's major or minor or patch may or may not contain breaking changes but there is no way to check or know that when doing a simple version bump. having this will be a kind of notifier to users.
A simple use-case of this will be dependencies management bots eg - `dependent-bot` or `renovate` etc. I am pretty sure its kind of overwork or exhausted to feel when reviewing any PR by these bots as we need to manually look the changelog or sometimes compared commits when changelog is not present to know whether the release contains any breaking changes or not.
having this proposal supported by the bots , now our bots can have an understanding of the content better. So even we can configure the bot to auto-merge the PR if the breaking change flag (v0.0.0.X) is set to `0`

_I am not sure whether calling the number's position as a `bit` is right, please correct me if required_

**Comment by jwdonahue** [comment]
The standard already has breaking changes covered.  You bump the major version and no minor or patch change should ever be released with a known breaking change.

For bots, take a look at [VersionMeta](http://versionmeta.org/) and [VersionSchema](http://versionschema.org).

**Comment by anikethsaha** [comment]
true, But there are cases when we don't have any breaking changes in the major release. My point is that having breaking changes with a release is too unpredictable. even patch release comes with breaking changes.

**Comment by ljharb** [comment]
If there’s no breaking changes, why is it a major? That’s the sole purpose of a major version.

**Comment by anikethsaha** [comment]
> If there’s no breaking changes, why is it a major? That’s the sole purpose of a major version.

May be to land up a major feature. !!

**Comment by ljharb** [comment]
That'd be a semver-minor, regardless of the desired [sentimentality](http://sentimentalversioning.org) of the feature.

**Comment by anikethsaha** [comment]
Okay . 
What would you consider a release of migrating the codebase to typescript?
I would consider it as major but this won't break explicitly any API so I wouldn't consider this as breaking change.

Right ?

**Comment by sungam3r** [comment]
Breaking for whom?

**Comment by anikethsaha** [comment]
> Breaking for whom?

I didnt get this !!!

**Comment by sungam3r** [comment]
OK. You have changed the internal mechanisms. Clients do not know anything about this and should not know.

**Comment by anikethsaha** [comment]
> Clients do not know anything about this and should not know.

Should not know about breaking changes ?

Why not ?

**Comment by sungam3r** [comment]
Once again.

> but this won't break explicitly any API 

So there are no breaking changes for clients.

> Should not know about breaking changes ?

The fact is that the concept of _breaking_ changes itself is not applicable to internal server changes.

> Why not ?

And what is the use for clients from this? They are not interested. They do not work with the server implementation, but with its abstraction through the api boundary.

**Comment by sungam3r** [comment]
By the way, if you are worried about marketing goals, you can simply version the server implementation and its api separately.

**Comment by ljharb** [comment]
@anikethsaha changing from JS to TypeScript - or any other language - is utterly irrelevant. If the compiled/transpiled output behaves the same, then it's a patch. If it behaves differently (including its API surface, peer deps, etc), then it's the *behavior change* that determines the semver, not whatever flight of fancy you happen to author it in.

**Comment by anikethsaha** [comment]
Ohh cool 👍 
thanks @ljharb @sungam3r @jwdonahue for responding
