### ISSUE TITLE
clarification on the ordering of pre-releases

### ISSUE THREAD

**Issue by mastupristi** [semver/semver#551]
referring to point 11:

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order.

So the following precedence apply:
1.2.3-alpha < 1.2.3-beta < 1.2.3-delta <1.2.3-gamma
despite the fact that in the Greek alphabet the order is

1. alpha
2. beta
3. gamma
4. delta

is that correct?

best regards
Max

**Comment by klehelley** [comment]
That is indeed correct.
