### ISSUE TITLE
SemVer URL

### ISSUE THREAD

**Issue by medesaties** [semver/semver#553]
Why does the URL have a `v`?
https://semver.org/spec/v2.0.0.html

Is “v1.2.3” a semantic version?
No, “v1.2.3” is not a semantic version.
https://semver.org/spec/v2.0.0.html#is-v123-a-semantic-version

I'm sorry if it's a stupid issue!

**Comment by ljharb** [comment]
Because the prefix indicates it’s a version number.

**Comment by medesaties** [comment]
It should be https://semver.org/spec/2.0.0.html, shouldn't it?

**Comment by medesaties** [comment]
> It should be https://semver.org/spec/2.0.0.html, shouldn't it?

To be Semantic.

**Comment by ljharb** [comment]
I’m not sure why the exact url format matters here; an URL part isn’t a semver version anyways.
