### ISSUE TITLE
query: re semver pronounciation

### ISSUE THREAD

**Issue by SignpostMarv** [semver/semver#562]
is `1.23` "one point twenty three" or "one point two three", i.e. to differentiate from `1.2.3` as "one point two point three"?

**Comment by ljharb** [comment]
Yes. Each part would generally be pronounced independently, eg, `1.23.0` is "one point twentythree point oh" and `1.2.3` is "one point two point three"

**Comment by SignpostMarv** [comment]
> Yes. Each part would generally be pronounced independently, eg, `1.23.0` is "one point twentythree point oh" and `1.2.3` is "one point two point three" (`1.23` is not a valid semver version, so i assume you meant `1.23.0`)

yes, although shorthand pronunciation is a separate issue that I'm not particularly fussed about being described in the spec (1.23 could be an alias for 1.23.0 or the entire 1.23.x release set depending on context).

**Comment by ljharb** [comment]
sure, but in either case you'd say "one point twentythree" :-)

**Comment by jwdonahue** [comment]
Actually, I am pretty sure it should read as "1 dot 23" so as not to confuse it with rational numbers in any respect.

**Comment by ljharb** [comment]
fair, i actually say dot and not point now that i think about it

**Comment by alexandrtovmach** [comment]
@SignpostMarv Seems like this issue resolved, thanks to @ljharb and @jwdonahue for answers
