### ISSUE TITLE
Mnemotechnic : remember ^ versus ~

### ISSUE THREAD

**Issue by cyrilchapon** [semver/semver#564]
Hey !

While I strongly understand `~` versus `^` behavior; I always struggle at remembering which one does what I think it does.

Roughly, I always re-read the doc; find the information, and tell myself "Ok, caret equals patch; tild equals minor + patch", and always forget it.

Does anyone knows some Mnemotechnic to learn it for good a single time ? 😄

**Comment by klehelley** [comment]
This repository is about the Semantic Versioning specification, that does not use nor define the `~` and `^` prefixes. Maybe you meant to post your question at https://github.com/npm/cli or https://github.com/npm/node-semver?

**Comment by cyrilchapon** [comment]
I'm using Node.js but that's not really a Nodejs specific question (composer, https://devhints.io/semver).

Though, I was sure the semver **ranges** was defined in the spec; and I'm very surprised to discover it's not the case !

**Comment by cyrilchapon** [comment]
Well; additional question. What spec / standard defines "semver ranges" ? Is that a commonly-used format without being backed by a spec ?

**Comment by ljharb** [comment]
The caret points up, because it means “this one, up to the next major”. The tilde looks like a hand waggling in place, meaning “kind of like this one, the same minor”.

npm defined ranges for itself with https://npmjs.com/semver, whose implementation is effectively the spec.

**Comment by Seldaek** [comment]
Composer implemented mostly-node-compatible [range constraints](https://getcomposer.org/doc/articles/versions.md#writing-version-constraints) to help with "mental" interoperability as most PHP devs using Composer also use npm to some extent. But indeed the semver spec defines none of this. This spec is only describing how to choose a version number when publishing a new release.
