### ISSUE TITLE
How to specify variants (language, architecture, etc.)

### ISSUE THREAD

**Issue by thomedes** [semver/semver#570]
It would be nice if there was a standard way to specify variants of the same thing.

Example, having:

-  FOO-spanish-i386  X.Y.Z
-  FOO-french-arm  X.Y.Z

I'd like to be able to incorporate the different variants in the versioning string in a standard way.

**Comment by ljharb** [comment]
Different package names, or as a prerelease?

**Comment by thomedes** [comment]
Different package names. Now I see my mistake, I actually typed faster than I thought.

If you effectively make different variants of the same product, each having a set of keys/values that identifies them (like `{ "arch": "i386", "lang": "en_UK" }` Then the version is just one more value to save in the set, like `{ "arch": "i386", "lang": "en_UK", "version": "X.Y.Z" }`.

I would be wrong to store all that info in the version string.

It would be a different project to create a semantic product identifier string allowing a set of key/values to be specified in a formal way. Probably better to close this Issue.
