### ISSUE TITLE
Setup Stale Bot's

### ISSUE THREAD

**Issue by jeme** [semver/semver#572]
It seems this repo could make good use of a bot that checks stale issues etc.

For now that bot is called @jwdonahue it seems (judging from https://github.com/semver/semver/pull/519#issuecomment-641401616) - but I don't think that is a Fair use of his time when this could just as well be automated using something like https://probot.github.io/apps/stale/ - and I am sure there are other automated solutions out there to the same problem.

So I would suggest to free up some of @jwdonahue 's time and add a real bot. I haven't used it in the past, so I would wan't to familiarize my self with it before adding a PR on it, so if anyone else already has the experience, maybe they can grab this if they have the time.

**Comment by jeme** [comment]
@ljharb While i agree that outright closing issues just because they haven't received activity for a large period of time isn't constructive, keeping issues that will never move further open forever isn't productive or constructive either.

But keep in mind, such a bot would not close such issues immediately, instead it marks an issue as stale, noting that it will at a later time close the issue if it doesn't receive any more activity. (That is pretty close to what @jwdonahue  has  been doing, with the exception that he asks the author to close it, but what if the author never checks in anymore? shall it then just stay open forever?)

Ofc. it can be controversial since it may in some cases call for the unwanted "+1" response, (it should really have a 'snooze' option one could click, so you can say keep this issue alive but don't pollute the thread >.<)...

I have seen such a bot be put to good use for projects where issues become so old that no one really cares about them anymore, as such, no one feels anything about them being closed by a bot, and you can always reopen them if you care (which bot's often encourage one to do)...

So all in all, such a bot can be implemented in a "user-hostile" way, but if you take care, it can also be done in a way that is very respectful and acceptable from a user perspective.

**Comment by ljharb** [comment]
I think a bot to mark issues as stale is fine - I’m objecting to a non-human *closing* issues, specifically.

**Comment by jeme** [comment]
> I think a bot to mark issues as stale is fine - I’m objecting to a non-human closing issues, specifically.

I think that is possible as well, and that could be done to begin with. And then see what effect it had and then revise after some time.

**Comment by jeme** [comment]
Anyways, since it seems there are more objections to this than otherwise.

For other reasons I will REDACT my content after 24 Hours.

**Comment by jeme** [comment]
After a bit of thought, i realize that comment could very likely be misunderstood by you two...

Let me therefore assure you that that action and comment had absolutely nothing to do with you guys - nor your opinions - which i respect very much.

So I am VERY SORRY if it came across like that, as if you had any cause it that action, you did absolutely not... I have just chosen to pull my involvement in this project completely.

**Comment by FichteFoll** [comment]
> One of the real problems here is that GitHub doesn't provide finer grained control of privileges. You can't give tagging privileges to someone without also giving them the keys to the entire kingdom (write access to the repo).

Github added the "Triage" access level some time last year, iirc, which allows exactly for what would be needed: manage issues without write access to the repository.
