### ISSUE TITLE
Please make my ban permanent, I won't be returning anyway.

### ISSUE THREAD

**Issue by jwdonahue** [semver/semver#574]
I wish you all the best, but I think you are too PC for my tastes.

**Comment by FichteFoll** [comment]
What happened here? I have been following the repository's issues on and off for years, but I need more context.

**Comment by jjlharrison** [comment]
See #571

**Comment by FichteFoll** [comment]
Thank you for the reference. I opt to refrain from commenting on the situation otherwise.

**Comment by alexandrtovmach** [comment]
@jwdonahue You made a lot of contributions to this project, perhaps even more than anybody, please, reconsider. I feel like it's my fault and I'm really sorry and sad to see you go. Guy with your experience would really help to move this project forward and I wish that this situation would never happen, and we'd just move on and focused on making open source better.

**Comment by jwdonahue** [comment]
@alexandrtovmach, it's not your fault (you should easily figure out how to contact me directly).  Please don't let any of this dampen your zeal for the project.  You're doing a good job and the project needs you.  I'll be focusing on what comes after SemVer 2.0.0.

I've been refraining from criticizing the current maintainers, since they took over.  @steveklabnik has contributed more effort than most over the past year, but the rest of them seem to be more willing to let the project stagnate, than the previous two maintainers.  I fully understand their motivations, but I don't think they've acknowledged the level of frustration that many in our community have felt over the past six or seven years or so.  

I certainly never anticipated the COC being applied the way it has recently, when I pushed to have it committed to the repo (I think somebody warned me about this actually).  While I think the maintainers should not hesitate to step in when a community member is being harassed by someone unnecessarily, I think the maintainers should have thicker skins.  They volunteered to run this project, and they can do with it as they see fit, so I have nothing more to contribute as long they think indirect's actions w.r.t. @runeimp have been reasonable.

**Comment by Saklad5** [comment]
I feel like this “issue” should be closed.

**Comment by ljharb** [comment]
@jwdonahue has your position changed?

**Comment by jwdonahue** [comment]
Actually, they never suspended or banned me.
