### ISSUE TITLE
 What's the right way to upload a minor version in 'semver'?

### ISSUE THREAD

**Issue by SangHakLee** [semver/semver#582]
There are two ways.

My thoughts are: (`way-1`)
> current version is **1.10.5**
> and there was a minor version update, so it was changed to **1.11.0**
>
> The following cases are the same.
> - `major` **1.10.5** -> **2.0.0**
> - `patch` **1.10.5** -> **1.10.6**

However, other team members think so: (`way-2`)
> current version is **1.10.5**
> and there was a minor version update, so it was changed to **1.11.5**

--- 

Which of `way-1` and `way-2` is more suitable for semver?

**Comment by ljharb** [comment]
Absolutely way-1. The spec explicitly says this here: https://semver.org/#spec-item-7

> Patch version MUST be reset to 0 when minor version is incremented.

**Comment by SangHakLee** [comment]
@ljharb Thank you.

It was clearly stated in the document.
I should have read the document in more detail. 

---

**Additionally**
> Patch and minor version MUST be reset to 0 when major version is incremented.

---

**It became clear and certain!**

**Comment by alexandrtovmach** [comment]
@ljharb thanks for answer 👍 
@SangHakLee Closing as solved, feel free to re-open if there are still any questions
