### ISSUE TITLE
CC

### ISSUE THREAD

**Issue by Miu98** [semver/semver#600]

**Comment by Pablo-No** [comment]
Do you mean Creative Commons?

**Comment by stephanmg** [comment]
@Miu98 could you please clarify?

**Comment by Pablo-No** [comment]
@stephanmg Do you mean that my comment is spam (I can delete it), or that @Miu98 issue is spam?

**Comment by Nixinova** [comment]
That OP's is spam, is almost definitely what they meant

**Comment by steveklabnik** [comment]
Yes, it appears so.
