### ISSUE TITLE
Regex examples contain invalid semvers as valid semvers

### ISSUE THREAD

**Issue by sschuberth** [semver/semver#624]
My understanding from reading [9.](https://semver.org/#spec-item-9), looking at the [BNF](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) and reading comment like [this](https://github.com/semver/semver/issues/45#issuecomment-8173992) is that *if* there is both a pre-release and build meta data part, the pre-release part has to come first. Still, the [online](https://regex101.com/r/Ly7O1x/3/) [regexes](https://regex101.com/r/vkijKf/1/) contain e.g. `1.1.2+meta-valid` as a valid semver, whereas it IMO should be `1.1.2-valid+meta`.

**Comment by klehelley** [comment]
Hyphens are allowed in build metadata. As a consequence, `1.1.2+meta-valid` is a valid SemVer string, and should be interpreted as such:

* Major : `1`
* Minor : `1`
* Patch : `2`
* Pre-release : (none)
* Build metadata : `meta-valid`

**Comment by sschuberth** [comment]
Thanks for the clarification. I was confused by `<build identifier> ::= <alphanumeric identifier> ...` as I though it's clear that "alphanumeric" are just letters and digits, but in fact it is `<alphanumeric identifier> ::= <non-digit> ...`, and `<non-digit>` includes `"-"`.
