### ISSUE TITLE
Common or Proper Noun?

### ISSUE THREAD

**Issue by DeveloperC286** [semver/semver#648]
`Semantic Versioning` is a proper noun because it is the name of the specification, hence the capitalisation. However, is `Semantic Version` a common or proper noun? My instinct says it is a proper noun because it is the name for a version following Semantic Versioning.

However, I noticed `semantic version` was not capitalised in the FAQ. Just wanted to double-check so I can use it correctly.

I am aware that even though I am a native speaker, my grasp on the grammar is not great, so I am probably wrong.

**Comment by ljharb** [comment]
Regardless of what might be prescriptively correct, I've only ever seen "semantic version" - ie, the noun version, and the adjective semantic, used uncapitalized.

**Comment by DeveloperC286** [comment]
> Regardless of what might be prescriptively correct, I've only ever seen "semantic version" - ie, the noun version, and the adjective semantic, used uncapitalized.

Okay I will use the lowercase version 👍 Thanks...
