### ISSUE TITLE
Invalid version string "8.x-1.x-dev" 

### ISSUE THREAD

**Issue by jderusse** [semver/semver#671]
When analyzing a `composer.lock` file sent by customer, I discovered this package:

```json
        {
            "name": "foo/bar",
            "version": "8.x-1.x-dev",
            "...": "truncated"
        }
```

When parsing the version, Semver throws an `UnexpectedValueException`.

note: This exception, is also thrown when running `$composer->getLocker()->getLockedRepository()` when the `ArrayLoader` is loading the package.

So, I wonder, if this is a legitimate version, and if we should patch Semver?

**Comment by jjlharrison** [comment]
I think https://github.com/npm/node-semver would be the correct repository for this issue. This repository is for the semver specification.

**Comment by ljharb** [comment]
Not node; composer is PHP.

**Comment by steveklabnik** [comment]
Yes, this bug should be compiled against composer, not against the specification. Thank you!

**Comment by steveklabnik** [comment]
(on a non-procedural note: this is not a valid semver version. Now, usually what is put into files is a *range*, not a *version*, and ranges are not technically in the semver spec yet. https://github.com/semver/semver/pull/584 is the current draft of the proposal for adding it to the spec. I still have not had the time to actually review it yet. 2020 was quite the year. but it is likely (though I haven't used composer so i can't be 100% sure) that you'd want to compare this to that, but you'd really need the composer maintainers to say. it is very clearly not a semver version though.)

**Comment by jderusse** [comment]
oh sorry about the wrong repo
