### ISSUE TITLE
Atom.AlongRizal/contributing.AlongRizal/contributing guidelines.AlongRizal/code of conduct.AlongRizal

### ISSUE THREAD

**Issue by AlongRezal** [semver/semver#676]

**Comment by vieclamphothongvietnam** [comment]
⚠️📣Bạn đang cần tìm việc làm nhưng chưa lựa chọn được ?
📛📛 TUYỂN GẤP 200 BẢO VỆ 𝐍𝐀𝐌/𝐍𝐔̛̃ -𝟳.𝟮𝗧𝗥/THÁNG+𝗕𝗔𝗢 𝗔̆𝗡 𝗢̛̉ TẠI #BẮCNINH
🎁Thu nhập: 𝟳.𝟮𝟬𝟬.𝟬𝟬𝟬đ - 𝟳.6𝟬𝟬.𝟬𝟬𝟬đ/tháng
➡️Yêu cầu: Nam, nữ trong độ tuổi lao động, không xăm trổ, sức khỏe tốt, không tiền án tiền sự.
➡️Công việc và địa điểm làm việc Cty Hồng Hải Quế Võ Bắc Ninh
♦️𝑷𝒉𝒐̉𝒏𝒈 𝒗𝒂̂́𝒏 đ𝒂̣𝒕 đ𝒊 𝒍𝒂̀𝒎 𝒏𝒈𝒂𝒚.
********************************************
☘ QUYỀN LỢI KHÁC:
🍔Nhà máy 𝗯𝗮𝗼 𝗮̆𝗻 02 bữa 𝒎𝒊𝒆̂̃𝒏 𝒑𝒉𝒊́
➡️Có 𝒏𝒉𝒂̀ 𝒐̛̉ 𝑴𝒊𝒆̂̃𝒏 𝑷𝒉𝒊́ cho nhân viên. Nhà ở rộng rãi, sạch sẽ.
➡️Ca làm việc: 12 tiếng/ngày (7h00-19h00 hoặc 19h00-7h00)
🍁 Được đóng BHXH, BHYT, BHTN từ tháng thứ 2 trở đi.
🎁 Thưởng Lễ/Tết theo quy định Công ty
********************************************
YÊU CẦU HỒ SƠ:
➡️ Sơ yếu lý lịch (Bản gốc)
➡️ CMND, Sổ hộ khẩu, Giấy khai sinh, Bằng tốt nghiệp (Sao y dấu đỏ)
➡️ Giấy xác nhận nhân sự (bản gốc)
➡️ Giấy khám sức khỏe (cấp huyện trở lên - bản gốc)

☎️ Liên hệ đi làm: 𝟎𝟗83 969 298
♻️ Đăng ký Email
vieclamphothongvietnam@gmail.com
🎯LƯU Ý: Ứng viên khi đến phỏng vấn mang theo CMT gốc + Hồ sơ đầy đủ. #665

**Comment by vieclamphothongvietnam** [comment]
Ok #667
