### ISSUE TITLE
No API interface breaking change only behavior change? Should I bump minor version or patch version? 

### ISSUE THREAD

**Issue by zamronypj** [semver/semver#695]
I introduce internal behavior change in API but API interface does not change. What version to bump? minor or patch?

**Comment by ljharb** [comment]
Is the behavior something a consumer could rely on, in any way? If so, breaking. If not, patch.

**Comment by zamronypj** [comment]
@ljharb  To consumer of API, new behavior is more stable but with reduced performance. Is performance impact considered something a consumer rely on and warrant major version bump?

**Comment by ljharb** [comment]
By default and in most cases, absolutely not. If you consider it a critical part of your project's API contract, then you might indeed want it to be major.

In any case tho, "same semantics" without any "new feature" isn't minor, it's patch or major.
