### ISSUE TITLE
[Question] What is the logic behind appending <x.y.z> part to prerelease versions

### ISSUE THREAD

**Issue by RomanDavlyatshin** [semver/semver#696]
**The example**:
1. Imagine we have a previous version being `1.0.0`;
2. Work on multiple features is in progress: `feature/a`, `feature/b`, `feature/c`.
3. Each branch is developed and tested in isolation. In order to facilitate a consistent testing process, we create prerelease versions from each branch (`x.y.z-feature-a.0`, `x.y.z-feature-a.1`, ...) each one representing a certain patch/fix introduced during back-and-forth work on a feature.
4. When features are done, release branch is created, e.g. release `1.1.0`, which will include `x.y.z-feature-a.999`, `x.y.z-feature-b.100` and `x.y.z-feature-c.42`.
5. Feature `feature/c` gets postponed to a later release, but now its `x.y.z` part is incorrect because it's pointed to a release **we expected** to merge it into.

**Question 1:** Why a prerelease `<major.minor.patch>` part is pointing towards a **future** version, rather than the one prerelease is **based on**?
It seems to me that making `x.y.z` part of a **prerelease** version point to a "previous" version it's **based on** makes more sense, than pointing it to some arbitrary release, that might change versions at any time.

____________________________________________________________________________________________________________________
**The example**:
When creating a prerelease semver infers version from the current one, and the following example (using Semver's npm package)
```
console.log(semver.parse('1.0.0').inc('prerelease', 'new-feature-name').version)
```
yields
```
1.0.1-new-feature-name.0
```
as you can see, besides adding a "prerelease" part, Semver incremented a PATCH version.

**Questions 2**: What is the reasoning behind incrementing a PATCH version by default?
**Questions 3**:  Can one force Semver to bump a MINOR version, in a case when changes introduced in `prerelease` **will** add a new feature? Or force a MAJOR version bump, when changes **will** introduce a breaking change?

**Comment by jjlharrison** [comment]
I think this issue relates to https://github.com/npm/node-semver, not this repository.

**Comment by ljharb** [comment]
A prerelease is “pre” a release - before it. Linguistically speaking nothing else would make sense for that name.

**Comment by RomanDavlyatshin** [comment]
@jjlharrison I've encountered the same behavior with `npm version`, so I assumed it's a trait of a specification, not implementation. If I am wrong, I would gladly close that issue and re-open it to another rep.

**Comment by ljharb** [comment]
@RomanDavlyatshin there isn’t anything in semver for that besides a prerelease - the version it’s based on is irrelevant, only the version it’s targeted to be released as is useful.

**Comment by RomanDavlyatshin** [comment]
@ljharb yes, and that is what causing the issue, in a scenario when the feature gets postponed to another release. (And that confuses me 🤔 )
I guess I'll wait for a day or two for comments on the issue, in case anybody else got something to say on that one and then will close it.

**Comment by jjlharrison** [comment]
> @jjlharrison I've encountered the same behavior with `npm version`, so I assumed it's a trait of a specification, not implementation. If I am wrong, I would gladly close that issue and re-open it to another rep.

`npm version` uses node-semver too.

**Comment by ljharb** [comment]
@RomanDavlyatshin then it'd just go in a different prerelease. There's never a guarantee that a version will contain everything that a prerelease of it contains.

**Comment by RomanDavlyatshin** [comment]
> There's never a guarantee that a version will contain everything that a prerelease of it contains.

@ljharb That is exactly what I am pointing to 😃 
I simply dislike the fact, that the prerelease version name will have to be changed "midway" when it gets migrated to a new release.
This is kinda annoying because branches and artifacts with new names will no longer consistently reflect the whole history of a feature.

As there are no more suggestions, I'm closing the issue. Thank you, everybody 👍
