### ISSUE TITLE
Regex from semver.org not matching 0.0.1-SNAPSHOT.I.0285680

### ISSUE THREAD

**Issue by shoelzle** [semver/semver#702]
The version `0.0.1-SNAPSHOT.I.0285680` is not a valid semantic version.
The problem is the `0` after the dot, hence `0.0.1-SNAPSHOT.I.1285680` matches just fine.

But why must *multiple* digits in a numeric identifier not start with a zero ?

The relevant part from the semver.org BNF:
```
<numeric identifier> ::= "0"
                       | <positive digit>
                       | <positive digit> <digits>
```

**Comment by dtonhofer** [comment]
I would say, because if it's a number, it should be written canonically, without any leading zeros.

**Comment by shoelzle** [comment]
My mistake:
The suffix `0285680` is an example of a short commit sha and as such it is just not semver compliant to put it in the `pre-release` part of the BNF because it is not a `numeric identifier`. But it is a `build identifier`, so the following versions are semver compliant:
* `0.0.1-SNAPSHOT+I.0285680`
* `0.0.1-SNAPSHOT+I.1285680`

Thanks for the hint.
