### ISSUE TITLE
[Question] What if two variations of versions will merge and build system will change?

### ISSUE THREAD

**Issue by ankiedos** [semver/semver#704]
I have two variations of the same version: `0.1.0-beta+verbose` and `0.1.0-beta+noverbose`. That with `verbose` build metadata logs verbose information and  one with `noverbose` doesn't.
After this pre-releases I added new commandline option `--log`, which enables functionality of `verbose` variation and I want to create a merged version. Additionally, I changed build system from GNU Make and MinGW Make to CMake.

What version I have to bump in semver? Major or minor?

**Comment by ljharb** [comment]
Those are all prereleases - the next non-prerelease version is based on whatever the differences are between it and the last non-prerelease version.

**Comment by ankiedos** [comment]
But what if I have not any non-prerelease versions? 0.2.0 and never release version 0.1.0, or something different?

**Comment by ljharb** [comment]
You can start at any version, or skip any version.

**Comment by ankiedos** [comment]
Thank you.
