### ISSUE TITLE
Tag version is not creating in Orderwise

### ISSUE THREAD

**Issue by shilpabhapri** [semver/semver#705]
We have implemented Tag creation using Semantic versioning but today we observed that tag has not created in order wise and unable to proceed with further deployments as the incremental one tag is already been exists.
Example: previous tag: 2.9.8,  later minor bump deployment has happened so the tag got generated with this is: 2.10.0 and above to it there is patch deployment completed with tag:2.9.9 .. why is it? 
It should have created with 2.10.1 as per my understanding.
Could you please let us know the root cause of this and what is the permanent fix?

I have attached the Tags list.

![Tag issue](https://user-images.githubusercontent.com/38104365/119642093-fd795c80-be37-11eb-9594-c00ffbe6f676.JPG)

**Comment by ljharb** [comment]
That’s an issue with whatever is displaying those tags. Git (with the proper config), and GitHub, for example, sort tags in semver order, not lexicographical order.

**Comment by shilpabhapri** [comment]
Hi @ljharb .. Thanks for your response!!
Yes, we are using Semantic Versioning to create the tags automatically (git describe --tags) in our GitLab pipeline. And also choosing the appropriate Labels (Major-bump, Minor-bump and Patch) while creating the merge requests. Still we encountered this issue. Please let me know if any other reason on why the Tags have created in disorder?

**Comment by shilpabhapri** [comment]
Hi @ljharb 
Kindly help us in understanding what could be the reason for disorder Tag creation.

**Comment by ljharb** [comment]
@shilpabhapri a bug in gitlab. file it there.

**Comment by shilpabhapri** [comment]
Hello, ljharb ..
Thanks for your kind responses!!
