### ISSUE TITLE
should major versions be independent or consecutive

### ISSUE THREAD

**Issue by Tieske** [semver/semver#713]
consider making another, different, breaking change to an old version, e.g.:

- `1.0.0` introduces features `foo` and `bar`
- `2.0.0` removes feature `foo` (only retains `bar`)

what's the number of a new version based of of `1.0.0`, that removes feature `bar`, and retains `foo`?

Current "expectations" would probably be that it would become version `3.0.0` since, relative to `2.0.0`, we add feature `foo`, and remove feature `bar`. OR it is released as a different product/api. (Option A)

The alternate way of doing this would be to consider the `major` version to be just a unique identifier, and not caring about the number being consecutive. As such it could for example be released as `8.0.0`. (Option B)

The main difference is that Option B is more flexible from the publishers perspective, but does not define a natural "latest" version for the "consumer" of the api.

This issue came up when discussing semver/semver#712

**So question is**: since there is (I think) a natural expectation of major numbers to be consecutive, should the spec be updated to clarify to relation between two major numbers. I'm not proposing what it should be, just asking whether a clarification would make sense.

Edit: added the final question

**Comment by ljharb** [comment]
@Tieske anything that's not v1 or v2. It could be v3.0.0, or v12345.0.0, but it's not compatible with v1 or v2.

It's irrelevant whether or how it's related to v1 or v2 beyond that it's a breaking change from both.

**Comment by alexandrtovmach** [comment]
@Tieske is it helpful?

**Comment by Tieske** [comment]
I clarified the original post by adding a question. I think what @ljharb mentioned is the same as Option B in my post. But should we add a clarification to make it more explicit?

**Comment by alexandrtovmach** [comment]
I think this changes not required
