### ISSUE TITLE
Request to transfer maintainer role (NuGet rep)

### ISSUE THREAD

**Issue by anangaur** [semver/semver#719]
Hello @semver/maintainers, 

I am very excited to let you all know that @zkat, a member of the @NuGet team, has volunteered to the take up the maintainer role @semver. @zkat has been a huge proponent of SemVer in the @NuGet team and hence I believe they would be more active with some of the discussions happening here. 

Can you all approve the transfer request? Once we have all approvals, I can make the necessary change. 

Tracking approvals:
* [ ] @isaacs  
* [x] @indirect 
* [x] @steveklabnik 
* [X] @Seldaek 
* [ ] @dherman 
* [ ] @segiddins 
* [x] @anangaur 

Thanks,
Anand (@anangaur)

**Comment by anangaur** [comment]
Pinging explicitly for notifications: @isaacs  @indirect @steveklabnik @Seldaek @dherman @segiddins 

Hope you all are fine with this transfer. In the interest of time, unless I hear otherwise, I plan to initiate the transfer by end of the week.

**Comment by steveklabnik** [comment]
Checked my box. Quite happy to have @zkat around!

**Comment by indirect** [comment]
Huh, I remember checking my box back when this was posted and I guess it somehow didn’t take. Nice to have you, @zkat!

**Comment by ljharb** [comment]
What does “transfer” mean?

**Comment by zkat** [comment]
It means that I would get the access Anand currently has, and I'd be the one representing the NuGet side of things in this org, I believe :)

**Comment by ljharb** [comment]
Makes sense, thanks :-)

**Comment by anangaur** [comment]
We have 4/7 folks approving the transfer and no pushbacks. I have added @zkat as maintainer. @zkat, once you accept the maintainer role request, feel free to remove me from the list :)

**Comment by zkat** [comment]
@anangaur thanks for the invite. I think you need to remove yourself, so feel free to do that if that's what you want

**Comment by jwdonahue** [comment]
Don't forget to update the [CONTRIBUTING.md](https://github.com/semver/semver/blob/master/CONTRIBUTING.md) file.
