### ISSUE TITLE
Website replaced -- with – (endash) and --- with — (emdash)

### ISSUE THREAD

**Issue by Anderium** [semver/semver#726]
This is an incredibly small detail about the specification on the website. The example version `1.0.0-x-y-z.--` renders as `1.0.0-x-y-z.–` on the website. Where the `--` has been replaced with an endash: `–`. Similarly `1.0.0+21AF26D3----117B344092BD` renders as `1.0.0+21AF26D3—-117B344092BD`. The `---` has been replaced with an emdash: `—`.

Below some screenshots. The left is from the [markdown](https://github.com/semver/semver/blob/8b2e8eec394948632957639dfa99fc7ec6286911/semver.md) here on git and the right is from the [website](https://semver.org/spec/v2.0.0.html).

<img height="30" alt="Markdown of what becomes endash" src="https://user-images.githubusercontent.com/33520919/125637753-28de2e95-96a4-4c3a-8150-26dad59b155a.png"> <img height="30" alt="The endash instead of two hypens" src="https://user-images.githubusercontent.com/33520919/125637755-0d0a8f6e-bb07-4d49-a86b-775ef0a66343.png">
<img height="30" alt="Markdown of what becomes emdash" src="https://user-images.githubusercontent.com/33520919/125637741-1b78e9c7-1fd5-4569-b2c4-73e48160408c.png"> <img height="30" alt="The endash instead of three hypens" src="https://user-images.githubusercontent.com/33520919/125637752-714e30d9-937d-4606-82b0-bee478dec10b.png">

I know that LaTeX interprets these sequences, so my guess is that somewhere in the process of generating the website a tool converts `--` and `---`, while it shouldn't in this case.

**Comment by Nixinova** [comment]
Duplicates https://github.com/semver/semver.org/issues/291
