### ISSUE TITLE
Question: Do bump in version implies an actual change for SemVer?

### ISSUE THREAD

**Issue by pak3nuh** [semver/semver#807]
It might seem like common sense that if a version changes, then something in the code changes, but there are nuances.

For instance there might be branding strategies like bumping a product version to a new major early or there might side effects of bundling components where we make an increment on one of the components, but all others are bumped just because they belong to the same global package.

I've looked at the spec and I've only seen that if something changes, then it MUST be versioned, but haven't seen the opposite. If something hasn't changed, CAN it be versioned?

**Comment by ljharb** [comment]
Yes, a change is not required - although bumping a version when no change is included causes churn for consumers, and so may be seen as a hostile act if done frequently.

**Comment by JohnTitor** [comment]
I think this is not something to clarify on the semver specification, so just closing in favor of the above answer.
