### ISSUE TITLE
Semantic version sorting issue

### ISSUE THREAD

**Issue by Sreejith-Websphere** [semver/semver#812]
In our project we are using antora 3..0.1 and in docs-playbook urls latest_version_segment key is added to convert actual version to symbolic version. Since our version used in antora.yml is of this form eg: 22.0.0.1, so when we have 22.0.0.1,22.0.0.2,22.0.0.3 antora still shows 22.0.0.1 as latest

Saw Semantic Versioning Specification where they mentioned version should be as x.y.z, so tried with eg: like 22.0.1, 22.0.2, 22.0.3 then it start giving 22.0.3 as latest

But our project needs version as 22.0.0.1, so how to sort and get the latest

**Comment by steveklabnik** [comment]
22.0.0.1 is not a semantic version, and so sadly, this is something not under our control. You'd want to ask the antora project.
