### ISSUE TITLE
RFC 2119 link is broken

### ISSUE THREAD

**Issue by rayzchen** [semver/semver#815]
The RFC 2119 link at https://semver.org/spec/v2.0.0-rc.2.html#semantic-versioning-specification-semver links to http://tools.ietf.org/html/rfc2119 which gives:

![image](https://user-images.githubusercontent.com/54078384/159134227-278e89ca-18d5-4707-ae65-0be6a5d3f03d.png)

**Comment by bfernand** [comment]
The correct link is: https://datatracker.ietf.org/doc/html/rfc2119

**Comment by dkg** [comment]
I recommend using https://datatracker.ietf.org/doc/html/rfc2119 or  [BCP14](https://www.rfc-editor.org/info/bcp14) which also includes the disambiguation in [RFC 8174](https://datatracker.ietf.org/doc/html/rfc8174/), which is applicable to the semver document.

**Comment by RoystonS** [comment]
The original http://tools.ietf.org/html/rfc2119 link which was reported as broken is now working, and automatically redirects to https://datatracker.ietf.org/doc/html/rfc2119.

**Comment by ralphie79** [comment]
> The original http://tools.ietf.org/html/rfc2119 link which was reported as broken is now working, and automatically redirects to https://datatracker.ietf.org/doc/html/rfc2119.

The redirect works only for HTTPS, and not HTTP.
