### ISSUE TITLE
Warning when bundling with rollup: "Circular dependencies"

### ISSUE THREAD

**Issue by IdkMan2** [semver/semver#825]
When I try to bundle my library (with semver as a dependency) with rollup I get the following warning:

```
(!) Circular dependencies
../node_modules/semver/classes/comparator.js -> ../node_modules/semver/classes/range.js -> ../node_modules/semver/classes/comparator.js
../node_modules/semver/classes/comparator.js -> ../node_modules/semver/classes/range.js -> /Users/arek/Documents/CodeCloud/Node/next-recompose-plugins/node_modules/semver/classes/comparator.js?commonjs-proxy -> ../node_modules/semver/classes/comparator.js
```

The library on which I am working is public, so feel free to play with rollup yourself (located under /lib directory in monorepo):
https://github.com/IdkMan2/next-recompose-plugins

**Comment by ljharb** [comment]
That package is https://github.com/npm/node-semver - not this repo.

**Comment by IdkMan2** [comment]
Mistake, sory mate.
