### ISSUE TITLE
Should you use alpha/beta in a 0.y.z version?

### ISSUE THREAD

**Issue by katistix** [semver/semver#852]
I have a project currently on 0.2.2. After adding some features it will increment to 0.3.0, but the current available version is not complete. (To be more precise, it's an API where you can upload and delete files on a server) but right now you can only upload. I see the upload/remove as a SINGLE feature.

Can I release the current version under 0.3.0-alpha.1 to signal the fact that it is feature incomplete? Or is the alpha just for versions 1.0.0 and above?

**Comment by ljharb** [comment]
Yes, you can.

**Comment by katistix** [comment]
Thanks

**Comment by Nixinova** [comment]
You can do whatever you want with pre-release tags. Pre/post-1.0 doesn't mean anything in this case.
