### ISSUE TITLE
What is API in your context?

### ISSUE THREAD

**Issue by ksomov** [semver/semver#865]
You write: [...as they do not influence public API...; ...the huge audience which will be presented with a fait accomplished returns of former behavior of API is better to release new release...; ...When you declare outdated a part of public API, you have to...; ...If you have stable API on which users depend, the version has to be 1.0.0...]
Explain that such API?

**Comment by alasdairhurst** [comment]
The API is essentially referring to the public interface of your application/library. For example a REST API, exposed functions, the way that it's bundled, requirements from the user's environment, etc...).

**Comment by JohnTitor** [comment]
See also [What is an Application Programming Interface (API) | IBM](https://www.ibm.com/cloud/learn/api) and [API - Wikipedia](https://en.wikipedia.org/wiki/API).
