### ISSUE TITLE
Implementations - Swift

### ISSUE THREAD

**Issue by sloik** [semver/semver#873]
Hi :)

For fun, I have started implementing the specification in Swift (https://github.com/sloik/Major.Minor.Patch). 

Are there more and where can I find them? Is there a place where I can add my library so other developers that would like to use it can easily find it?

Cheers :)

**Comment by JohnTitor** [comment]
AFAIK no, and I expect some might become outdated/abandoned so I wouldn't prefer to provide it as official.

I've created https://github.com/JohnTitor/awesome-semver to collect them as an unofficial list. Does it work for you?

**Comment by sloik** [comment]
Yes :D 

Do I need to create a PR or issue on that repository? :)

**Comment by JohnTitor** [comment]
No worries, I've added your repo: https://github.com/JohnTitor/awesome-semver/commit/2370decb8438c85f78e0157b181515774d24cb4e
I'm going to close this issue as resolved but if you know any other stuff to be added there, I'd love to see your PRs :)
