### ISSUE TITLE
semver version in yaml format

### ISSUE THREAD

**Issue by codehangen** [semver/semver#876]
Hi all.  I would like to know if you all have ever thought about creating a semver file in Yaml.  *Would it be possible to have a **semver.yaml** file?*

**semver.yaml**
```yaml
version_string:
   - 0.2.1
   - 2.10.5  
   - 1.0.1a
   - 1.0.1a2  
   - 1.0.1b      
   - 1.0.1rc1
```

**Comment by JohnTitor** [comment]
The current comment doesn't describe what that YAML file does, could you clarify? What do you want for the semver specification?

**Comment by JohnTitor** [comment]
> A Semver specification is a data type

Hmm, I don't think [specification **is** a data type](https://en.wikipedia.org/wiki/Specification_(technical_standard)).

> Therefore, it would make sense to have a formatted file... semver in yaml format....

So you want to express the specification with YAML? But your YAML file just lists version numbers and some even don't follow semver (e.g. `1.0.1a`).

> I would like to know if you all have ever thought about creating a semver file in Yaml.

AFAIK no.

**Comment by ljharb** [comment]
What is a “semver file”?

**Comment by ljharb** [comment]
@codehangen that doesn't clear it up. Semver means that the version triple - x.y.z (possibly with a prerelease or build identifier) - encapsulates the entirety of the semantics, which means that the format of the file containing it is utterly irrelevant.
