### ISSUE TITLE
Other then "Public API" can still use semver.org?

### ISSUE THREAD

**Issue by cies** [semver/semver#90]
It comes out of a practical example where I've used semver to over more then then "Public API".  Cases of things that need to be kept stable within a major-cycle:
- database schema (should be migrateable from any to any version within a major-cycle with the standard migration runner)
- file formats (only non breaking additions/changes allowed within major-cycle)
- network protocols
- API-calls it makes on other systems (just as much public API actually)

Maybe semver could be formulated in a way that it shows it naturally covers more the just "public API".

**Comment by jwdonahue** [comment]
See also:
#90
#314 
#331

**Comment by silkentrance** [comment]
Why is this still open? SEMVER is about an abstract versioning process. ABSTRACT means stable. What is proposed here is barely stable. We do not need such. We want stable processes. And we also do not want peops who cannot cope with stable processes. Go back into your holes. And stay there.

**Comment by ameenross** [comment]
Who's "we"? Go tell the PKZIP guys (and countless others) that they didn't build something stable...

You can stick to Semver as currently defined, some of us want to be able to say that our (file format|db schema|API|protocol|whatever) adheres to semver s/public API/interface/

**Comment by cies** [comment]
Well said @ameenross 

This is exactly what I meant. A single codebase might use semver in several places, for instance: it has a file format, and library API and a web API.

Now I do not have a problem with using semver in its current form for these purposes, I'll just make it clear in the README (or other documentation). I simply regret that semver is not advertising that it can be used as such.

**Comment by jwdonahue** [comment]
@silkentrance, I agree that we have too many of these old threads laying around, but I have not completed my review of all the open issues yet, so I have not recommended closing this particular issue until, I have gathered all the seemingly worthy similar instances of "API should be changed to X".  When I do, I'll pick one that is sufficiently representative or write one up if needed, and then ask for the all the me-too's to be closed.  I can think of strong arguments to replace most instances in the spec of API with Interface.  It seems to be a valid open issue to me.

**Comment by jwdonahue** [comment]
@cies 

I've tried to consolidate all of the "API should be changed X" and similar issues into #468. Please contribute to this discussion on that thread and close this one at your earliest possible convenience.

Thank you.

**Comment by cies** [comment]
Closed in favour of #468
