### ISSUE TITLE
Consider storing versions internally not in a string representation

### ISSUE THREAD

**Issue by budarin** [semver/semver#908]
https://marvinh.dev/blog/speeding-up-javascript-ecosystem/

please look at the paragraph "The curious case of semver"

**Comment by ljharb** [comment]
@budarin is this meant for https://github.com/npm/semver, perhaps?

**Comment by budarin** [comment]
> @budarin is this meant for https://github.com/npm/semver, perhaps?

The link is incorrect :(

**Comment by ljharb** [comment]
ah sorry, i meant https://github.com/npm/node-semver.

**Comment by budarin** [comment]
It's quite possible, but I didn't know about it - so I decided that it was about your package
If I made a mistake, you can close the issue

**Comment by ljharb** [comment]
This repo isn't for a package at all - it's the semver spec, which spans far beyond the JS ecosystem. There's no code here.

**Comment by budarin** [comment]
Ok
