### ISSUE TITLE
Why is it called "semantic" versioning? 

### ISSUE THREAD

**Issue by vls-tomra** [semver/semver#920]
I am a big fan of semver ever since coming across it about ten years ago. Today I asked myself where the "semantic" in the naming comes from and unfortunately have no idea. Maybe this can be added to the FAQ?

**Comment by wojtekxtx** [comment]
@vls-tomra thats excellent question 👍

**Comment by iago-lito** [comment]
I'd say it's because it's adding *meaning* to things like `1.5.8` which otherwise would be just a sequence of digits and dots.

**Comment by silopolis** [comment]
I think exactly what @iago-lito said.

**Comment by vls-tomra** [comment]
now that you say it @iago-lito, it seems kind of obvious. :-) However, when someone tells me "thats just semantics" I think of how things are worded. I guess semantic is the connection between meaning and the actual word. "Semantic Versioning" does have a better ring to it, than "logical" or "meaningful" versioning.
