### ISSUE TITLE
Semantic version increase by patch even if is hotfix

### ISSUE THREAD

**Issue by misecca** [semver/semver#929]
Actual situation:
- main: last tag 0.1.0
- create a new branch hotfix/0.1.0
- first commit on hotfix/0.1.0 generate a tag 0.1.1-hotfix.1 --> expected 0.1.0-hotfix.1

**Comment by jwdonahue** [comment]
> first commit on hotfix/0.1.0 generate a tag 0.1.1-hotfix.1 --> expected 0.1.0-hotfix.1

Commits should not generate SemVer tags.  Revision control systems already have there own way of versioning what's in them. Adding version information in a commit is faulty design and will not scale.  Build/package/release systems generate SemVer versionable artifacts, if those artifacts are universally unique per version string (hard to do at scale, but do-able).  Whether such systems label the repo hash with the generated version of the artifact(s) created from it, is a matter of taste, but there can be multiple unique artifacts for any given repo content hash, so you're concept of version labels on commits is broken.

**Comment by steveklabnik** [comment]
> There's no such thing as a hotfix in semver. 0.1.0 is fixed with 0.1.1.

This is correct, yes.
