### ISSUE TITLE
API is never defined

### ISSUE THREAD

**Issue by TedTschopp** [semver/semver#937]
This requirements document does not define what an API is.  With the level of specificity found on the website with regards to this definition, this is a big mix.

For example: Is the UI/UX covered under API.  So if I change the complete user flow and the colors and the screens, but none of that is available on an API that is remotely available, does this mean that the API hasn't changed?

**Comment by ljharb** [comment]
You define the API for your own project.

However, semver is typically used for projects that are consumed programmatically, which means that if there's a UI/UX at all (ie, something that renders, like an app, as opposed to something like a component that *gets* rendered), semver might not be appropriate.

**Comment by steveklabnik** [comment]
That is 100% correct, @ljharb . Thanks!
