### ISSUE TITLE
release versions keep jumping by 2

### ISSUE THREAD

**Issue by jonlittleopencomp** [semver/semver#953]
Has anyone had a issue with semver that its going up 2+ versions instead of just 1?

such as 

1.17.0 to 1.19.

Any idea how this can be implemented in such a way and if it can be tuned to work only 1 version up each release?

**Comment by ljharb** [comment]
Are you perhaps talking about a specific semver implementation? This repo is for the spec.

**Comment by jonlittleopencomp** [comment]
ok thanks.
