### ISSUE TITLE
Getting Semver Vercaode vulnarability 

### ISSUE THREAD

**Issue by SanthoshReddyTR** [semver/semver#977]
Hi Team,
 In our project we are getting semver vulnerability when we are updating semver 6.3.1/7.5.2/7.5.4 through,still it is picking 7.3.5 version in veracode scan.
Please find the below details
Angular CLI version 13.2.3
Angular core 13.2.2
Node 14.15.0
After updating node to 14.17.3 also same scan issue.

Please find the below screen shots and guide me on this semver vulnerability.
![image](https://github.com/semver/semver/assets/102598539/c1b0f610-a844-4210-8c28-a7adf00e1ab5)
![image](https://github.com/semver/semver/assets/102598539/b0412256-04ba-471a-b145-a0b483efacf9)

**Comment by ljharb** [comment]
I think you meant to file this on node-semver, not this repo.
