### ISSUE TITLE
2 PR Raised and Latest PR committed merged released version impacts the old PR version increament

### ISSUE THREAD

**Issue by gviswalingam** [semver/semver#999]
On my Initial Investigation, Identified that on commit #137 had Semver 1.0.1 and #138 commit with msg +semver: minor increase 1.1.0 as expected  #139 commit from same PR as expected sticked to Semver 1.1.0 , all these commits from Same PR #46 . Now the PR #45  which was raised prior  to this (PR#46) but commits were made after PR#46 was merged & released Semver were 1.1.0 , commit #140  without a +semver: minor msg , Semver 1.0.1. With commit msg +semver: minor , it increased to 1.1.0 (Technically expected version is 1.2.0) and following another commit with minor msg it increased to Semver 1.2.0 .

**Comment by Mlwody90n** [comment]
> On my Initial Investigation, Identified that on commit #137 had Semver 1.0.1 and #138 commit with msg +semver: minor increase 1.1.0 as expected  #139 commit from same PR as expected sticked to Semver 1.1.0 , all these commits from Same PR #46 . Now the PR #45  which was raised prior  to this (PR#46) but commits were made after PR#46 was merged & released Semver were 1.1.0 , commit #140  without a +semver: minor msg , Semver 1.0.1. With commit msg +semver: minor , it increased to 1.1.0 (Technically expected version is 1.2.0) and following another commit with minor msg it increased to Semver 1.2.0 .

**Comment by Mlwody90n** [comment]
lilapazoki66@gmail.com

**Comment by Mlwody90n** [comment]
> On my Initial Investigation, Identified that on commit #137 had Semver 1.0.1 and #138 commit with msg +semver: minor increase 1.1.0 as expected  #139 commit from same PR as expected sticked to Semver 1.1.0 , all these commits from Same PR #46 . Now the PR #45  which was raised prior  to this (PR#46) but commits were made after PR#46 was merged & released Semver were 1.1.0 , commit #140  without a +semver: minor msg , Semver 1.0.1. With commit msg +semver: minor , it increased to 1.1.0 (Technically expected version is 1.2.0) and following another commit with minor msg it increased to Semver 1.2.0 .

**Comment by Mlwody90n** [comment]
> On my Initial Investigation, Identified that on commit #137 had Semver 1.0.1 and #138 commit with msg +semver: minor increase 1.1.0 as expected  #139 commit from same PR as expected sticked to Semver 1.1.0 , all these commits from Same PR #46 . Now the PR #45  which was raised prior  to this (PR#46) but commits were made after PR#46 was merged & released Semver were 1.1.0 , commit #140  without a +semver: minor msg , Semver 1.0.1. With commit msg +semver: minor , it increased to 1.1.0 (Technically expected version is 1.2.0) and following another commit with minor msg it increased to Semver 1.2.0 .
